### ISSUE TITLE
Code that should be removed

### ISSUE THREAD

**Issue by prainho** [ericdc1/Dapper.SimpleCRUD#105]
In this method: public static Task<IEnumerable<T>> GetListAsync<T>(this IDbConnection connection, string conditions, object parameters = null, IDbTransaction transaction = null, int? commandTimeout = null)

this line is not used: var whereprops = GetAllProperties(conditions).ToArray(); and should be removed

**Comment by ericdc1** [comment]
thanks. will be fixed in next version
