### ISSUE TITLE
Bulk Insertion for Sqlite

### ISSUE THREAD

**Issue by ShadyAbuKalam** [ericdc1/Dapper.SimpleCRUD#107]
SimpleCRUD is cool but inserting a large dataset with it  in sqlite is problematic..
I have measured insertion of  430 rows with 29 columns

```
              foreach (var member in membersToInsert)
                {                 
                    DBConnectionManager.GetSqliteConnection().Insert(member);
                }   

```

The average time is ~ 15 seconds

I wonder if there is a better way to do it, or It would be a nice feature to have.

**Comment by Yousefjb** [comment]
Make a transaction and pass it to the `Insert `extention method. I've tried to insert 5000 rows of 7 Columns and was inserted in less than a second
