### ISSUE TITLE
custom type support

### ISSUE THREAD

**Issue by guyulmaz** [ericdc1/Dapper.SimpleCRUD#108]
Hello,
As you know dapper allow custom type convertion via SqlMapper.AddTypeHandler.
I'm using protobuf. So protobuf is generating the *.cs class.
I'm giving this class to insert statement.
As protobuf is not supporting DateTime, I write a costum type, EpocSeconds , to make convertion.
The problem is as EpocSeconds is not a simpletype so, SimpleCrud is ignoring it.
If there would be a way to teach SimpleCrud that EpocSeconds is also a simple type, and Dapper will convert it to DateTime during insert it would be super. 

public class EpocSecondsHandler : SqlMapper.TypeHandler<EpocSeconds>
        {
            public override void SetValue(IDbDataParameter parameter, EpocSeconds value)
            {
                parameter.Value = UnixTimeStampToDateTime(value.DateLong);
            }

            public override EpocSeconds Parse(object value)
            {
                EpocSeconds e = new EpocSeconds();
                e.DateLong= DateTimeToUnixTimeStamp((DateTime)value);
                return e;
            }
        }

SqlMapper.AddTypeHandler(new EpocSecondsHandler());

public sealed partial class EpocSeconds : pb::IMessage<EpocSeconds> {
...
private long dateLong_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long DateLong{
      get { return dateLong_; }
      set {
        dateLong_ = value;
      }
    }

my proto file
syntax = "proto3";
package tutorial;
option csharp_namespace = "xxx.xxx";

message XXX {
    int64					id = 1;
    EpocSeconds			deviceDate = 2;
}

**Comment by ericdc1** [comment]
It seems unlikely that we would build this. It seems to me this is outside the spirit of "simple crud".
