### ISSUE TITLE
Dapper.SimpleCrud Insert method only support int? as return value, not long?

### ISSUE THREAD

**Issue by guyulmaz** [ericdc1/Dapper.SimpleCRUD#109]
currently Dapper.SimpleCrud only support int? as return value for Insert. At db we are using bigint as primary key. So why SimpleCrud Insert method can not support long? Isnt it possible to add this? or is there a design limit or something?

**Comment by ericdc1** [comment]
This is possible. The default insert returns int but you can specify the return type as well. 


        public void TestInsertUsingBigIntPrimaryKey()
        {
            using (var connection = GetOpenConnection())
            {
                var id = connection.Insert<long>(new BigCar { Make = "Big", Model = "Car" });
                id.IsEqualTo(2147483650);
                connection.Delete<BigCar>(id);

            }
        }
