### ISSUE TITLE
Issue with many to many table

### ISSUE THREAD

**Issue by FredBell** [ericdc1/Dapper.SimpleCRUD#110]
I am trying to use SimpleCRUD for my project but I cannot make it work for all my many2many tables.
All the m2m tables are simply a 2 columns table both int. And of course the key are not identity column since the value comes from 2 other tables. The m2m columns also have FK constraints pointing to the primarykey column of 2 other tables.
Basically it is the classic m2m table design.
Also - for information - I am using SimpleCRUD 1.13

I have a class representing each m2m table:
	[Table("TableM2M")]
    public partial class ClassX
    {
        [Key][Required]
        public virtual int Discount_Id { get; set; }
        [Key][Required]
        public virtual int Manufacturer_Id { get; set; }
    }

First: I tried without key attributes: and got the "Entity must have 1 key property" exception

Second: So then I added the 2 [key] attributes since it is a composite key of 2 integers. I also added the [Required] attribute since both column are not identity columns.
This worked for Get method and I was able to retrieve the data.
But unfortunately I could not do an insert and got the exception: Insert<T> only supports entity with a single [Key]
                int? identity = db.Insert(dam); //throws exception

Third: I removed one key attribute on the second column.
This allowed me to select the data and to insert data. But of course when I tried to delete the record - simpleCRUD deleted all the records with the Discount_Id value and ignored the Manufacturer_Id value.
                int nbDeleted = db.Delete(dam);

What am I missing here? many2many tables are extremely common - so I have to assume it is supported by SimpleCRUD.
The correct usage would be to have both field marked (as in the example above) with the [Key] and [Required] attribute. But then the insert does not work.

If someone could help me with this that would be fantastic. Or please confirm this is not supported by SimpleCRUD - that would be helpful too.

Thank you for the help,

Frederic

**Comment by ericdc1** [comment]
this is outside the spirit of "simple". when I have these cases I use plain old Dapper
