### ISSUE TITLE
Problem with insert into table with NoIdentity columns

### ISSUE THREAD

**Issue by mbaghert** [ericdc1/Dapper.SimpleCRUD#111]
Problem with insert into table with NoIdentity columns

SQL Express 2008 
My problem has been solved
with change ModelGenerator.tt

In Line 72 :
![image](https://cloud.githubusercontent.com/assets/6413705/20763064/cc2d932c-b73d-11e6-8585-60eb715df97f.png)
changed to
![image](https://cloud.githubusercontent.com/assets/6413705/20763170/30548266-b73e-11e6-8eb9-5a6c4d5e4b10.png)

with these change add [Required] Tag to my code .

![image](https://cloud.githubusercontent.com/assets/6413705/20763244/683c22ec-b73e-11e6-8b0a-acce2d8e0fef.png)

**Comment by ericdc1** [comment]
thanks for the info. if anyone else has this need post here so we can consider adding to the codebase
