### ISSUE TITLE
About DeleteAsync

### ISSUE THREAD

**Issue by rhnkyr** [ericdc1/Dapper.SimpleCRUD#121]
Hi guys,

i have a table like this : 

```
[Table("UserImages")]
    public class UserImage
    {

        public int Id { get; set; }

        public int UserId { get; set; }

        public int TotalLike { get; set; }

        public string ImageName { get; set; }

        public bool IsApproved { get; set; }

        public DateTime CreatedDate { get; set; }

        public User User { get; set; }
    }
```

when i try to delete a row 

```
public async Task<int> DeleteImage(int id)
        {
            return await WithConnection(async db =>
            {
                var ret = await db.DeleteAsync<UserImage>(id);
                return ret;
            });
        }
```

which i debug it and id comes as a interger value

it throws  

Must declare the scalar variable "@Id".

What do i miss?

Thanks in advance

**Comment by ericdc1** [comment]
please see the unit tests - test.cs line 658 to see this working properly. let me know if that doesn't work for you.

**Comment by rhnkyr** [comment]
Hi @ericdc1,

I checked it out and i noticed that you first insert a row then you use that returned id as parameter. I want to run my code over existed row. That's i could not achieve.
