### ISSUE TITLE
_connection.Get<T>(new {Id=id}) fails for Anonymous parameter

### ISSUE THREAD

**Issue by duhowise** [ericdc1/Dapper.SimpleCRUD#122]
An exception of type 'System.NotSupportedException' occurred in Dapper.dll but was not handled in user code

Additional information: **The member id of type <>f__AnonymousType0`1**[[System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] cannot be used as a parameter value

**Comment by ericdc1** [comment]
not enough info to help
