### ISSUE TITLE
Enums as strings?

### ISSUE THREAD

**Issue by nitro52** [ericdc1/Dapper.SimpleCRUD#123]
We like to save our enums as strings so they are easily identified when looking directly at the data. 

Is it possible to save enums as strings with SimpleCRUD? It seems to be saving them as their numeric value.

**Comment by ericdc1** [comment]
This is just a matter of passing the value as a string. You can use .ToString() on the value.

**Comment by nitro52** [comment]
Wouldn't that require some intermediate db objects though that would have it's enum properties as strings then later map back to an object with enum properties?

**Comment by jboarman** [comment]
This would definitely be useful.  When working with a pre-existing model, it kinda sucks to have to re-work the model to convert enums to strings manually in a separate object before calling SimpleCRUD methods on the object.  :/
