### ISSUE TITLE
Model Generator Has Issues One Table With Two FK's pointing to the same Table

### ISSUE THREAD

**Issue by earlxtr** [ericdc1/Dapper.SimpleCRUD#125]
If I have a table called Color and another table called Car that has two FK references to Color called InteriorColorId and ExteriorColorId then the model generator gets mixed up. 

I have fixed it so it that works in my environment using standard conventions such as  "Id" for the primary key and the FK Keys using the referring table and ending in "Id".

I end up with fixes like these that would normally be broken if they are in the same table.

		public virtual IEnumerable<RelatedRevisonSection> SourceRevisionSections { get; set; }
		public virtual IEnumerable<RelatedRevisonSection> TargetRevisionSections { get; set; }

and this

		public virtual User OwnerUser { get; set; }
		public virtual User AssignedUser { get; set; }

I also used the .NET pluralizer on collection names.

I can upload the revised generator if that would help others with the same issues.

Just let me know where I can upload it to.

Thank you

Earl Teigrob
earlxtr@gmail.com

**Comment by ericdc1** [comment]
submit a pull request with the specific lines changed. I will be glad to review it and possibly include in the project
