### ISSUE TITLE
is it not support oracle?

### ISSUE THREAD

**Issue by Jinsheng-Peng** [ericdc1/Dapper.SimpleCRUD#129]
is it not support oracle?

**Comment by duhowise** [comment]
no comment has been provided on this question for a while now, But how soon will you be supporting Oracle ??

**Comment by ericdc1** [comment]
Please see:

https://github.com/ericdc1/Dapper.SimpleCRUD/issues/57
And
https://github.com/ericdc1/Dapper.SimpleCRUD/issues/74
