### ISSUE TITLE
Index out of bounds exception on TableName dictionary

### ISSUE THREAD

**Issue by DrWalks** [ericdc1/Dapper.SimpleCRUD#133]
Hey there,

I am currently using Dapper.SimpleCrud v 1.11.1 and over the weekend one of the applications started throwing an exception that started like this:

`
System.IndexOutOfRangeException: Index was outside the bounds of the array.     
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)     
at Dapper.SimpleCRUD.GetTableName(Type type) in 
C:\Users\Eric\Documents\GitHub\Dapper.SimpleCRUD\Dapper.SimpleCRUD\SimpleCRUD.cs:line 864     
at Dapper.SimpleCRUD.GetListAsync[T](IDbConnection connection, Object whereConditions, IDbTr
ansaction transaction, Nullable`1 commandTimeout) in C:\Users\Eric\Documents\GitHub\Dapper.
SimpleCRUD\Dapper.SimpleCRUD NET45\SimpleCRUDAsync.cs:line 77     at Dapper.SimpleCRUD.GetL
istAsync[T](IDbConnection connection) in C:\Users\Eric\Documents\GitHub\Dapper.SimpleCRUD\Dap...
`

The usage of the GetListAsync (Nothing fancy) looks like this:

`using (var conn = _repo.GetConnection())
            {
                var refList = await conn.GetListAsync<T>();
                return refList.ToList();
            }`

After some digging into SimpleCRUD.cs I can see that the TableName property uses a type of Dictionary<T,T> to implement the interface IDictionary<T,T> 

I believe it is possible through using the SimpleCRUDAsync.GetListAsync where it calls SimpleCRUD.GetTableName that there could be a concurrency insert within GetTableName when adding the type/table name mapping.

Is it possible to use the ConcurrentDictionary<T,T> type instead of the Dictionary<T,T> type to perform this operation in a thread safe manner?

**Comment by karolre** [comment]
For the same reason it's impossible to use SimpleCRUD in parallel tasks :/

**Comment by shenzhigang** [comment]
Just use ConcurrentDictionary instead of Dictionary.
