### ISSUE TITLE
Why are you using dynamic

### ISSUE THREAD

**Issue by prainho** [ericdc1/Dapper.SimpleCRUD#135]
Hello,

I've found this code and I don't know why are you using the dynamic here and every place you access custom attributes. Ex:

                var tableattr = type.GetCustomAttributes(true).SingleOrDefault(attr => attr.GetType().Name == typeof(TableAttribute).Name) as dynamic;

I think you should change it to something like this:
                var tableattr = type.GetCustomAttributes(true).SingleOrDefault(attr => attr.GetType().Name == typeof(TableAttribute).Name) as TableAttribute;

In this case I think it's slower using the dynamic than cast to the type.

**Comment by ericdc1** [comment]
Thanks for the feedback. I would be interested in a pull request if you are interested in working on it
