### ISSUE TITLE
When to support?  .net core

### ISSUE THREAD

**Issue by 18965824402** [ericdc1/Dapper.SimpleCRUD#136]
When to support?  .net core

**Comment by joseazevedo** [comment]
Copy the Single CS file to your project, insted of usgin nugget,

https://raw.githubusercontent.com/ericdc1/Dapper.SimpleCRUD/master/Dapper.SimpleCRUD/SimpleCRUD.cs

it works.

**Comment by jmanuelcorral** [comment]
Download my branch, and there is donetcore support, also we have published a nugget package:

Install-Package Dapper.SimpleCRUD.NetCore -Version 1.0.0

Regards,

**Comment by psantiago** [comment]
@ericdc1 the codebase should now support .net standard 2.0, but I don't believe a new nuget package has been uploaded yet.
