### ISSUE TITLE
Dapper UpdateAsync ignore column not working

### ISSUE THREAD

**Issue by MichaelZaslavsky** [ericdc1/Dapper.SimpleCRUD#142]
Hello,

I am using Dapper.Contrib library in C# and I faced some problems while trying to ignore a property in my class on an update operation.
I am using these methods:
Dapper.Contrib.Extensions.UpdateAsync & Dapper.Contrib.Extensions.InsertAsync.
My class looks like this:
public class MyTable
{
    public int ID { get; set; }
    public int SomeColumn1 { get; set; }
    public int SomeColumn2 { get; set; }
    public int CreateUserID { get; set; }
    public int UpdateUserID { get; set; }
}

In the update method I don't want to update the CreateUserID column and therefore, I need to ignore this property. (Note: On the insert, I want this column non-ignored).
I tried using [NotMapped], [UpdateIgnore] attributes but no help – the attributes are not ignoring this property.
[UpdateIgnore] 
public int CreateUserID { get; set; }

Can you help me figure out how to ignore this column when updating the table in the database? And why UpdateIgnore not working?

Thanks in advance.

**Comment by ericdc1** [comment]
Dapper Contrib is a separate project than this.
