### ISSUE TITLE
Support for Insert with TKey of type Guid?

### ISSUE THREAD

**Issue by bartcoppens** [ericdc1/Dapper.SimpleCRUD#145]
Assume records with an identity field of nullable type "Guid?".
Inserting a record with a null identity will result in "Object reference not set to an instance of an object".

This is due to the logic in the Insert method that attempts to get the Guid using this line:
(Guid?)idProps.First().GetValue(entityToInsert, null);

Suggested solution:
if (keytype == typeof(Guid))
            {
                var guidvalue = **(Guid?)**idProps.First().GetValue(entityToInsert, null);
                if (**!guidvalue.HasValue ||** guidvalue == Guid.Empty)
...

**Comment by bartcoppens** [comment]
Additionally the methods BuildInsertValues and BuildInsertParameters also have to allow Guid?

Suggested solution:
 if (property.Name.Equals("Id", StringComparison.OrdinalIgnoreCase) && property.GetCustomAttributes(true).All(attr => attr.GetType().Name != typeof(RequiredAttribute).Name) && property.PropertyType != typeof(Guid) **&& property.PropertyType != typeof(Guid?)**) continue;

**Comment by ericdc1** [comment]
Thanks for the suggestion. I would be interested in a pull request on this provided all tests still pass.
