### ISSUE TITLE
does Dapper.SimpleCRUD.ModelGenerator support MySQL

### ISSUE THREAD

**Issue by jimiatworking** [ericdc1/Dapper.SimpleCRUD#150]
I have issue to use Dapper.SimpleCRUD.ModelGenerator on MySQL to generator table class. Does this support MySQL ?

I got error in ModelGenerator.cs as below.

`// Failed to read database schema - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[Database], 			TABLE_SCHEMA AS Owner,  			TABLE_NAME AS TableName,  			COLUMN' at line 2
`

And app.config as 

```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
  <connectionStrings>    
    <add name="appsConnectionString" providerName="MySql.Data.MySqlClient"
       connectionString="server=127.0.0.1;port=3306;database=sakila;uid=root;password=abcdefg"/>
  </connectionStrings>
</configuration>
```

**Comment by ericdc1** [comment]
Probably not though I never tried. The intent was MSSQL
