### ISSUE TITLE
Not possible to call GetListAsync<T>(Transaction) without where clause

### ISSUE THREAD

**Issue by mcinnes01** [ericdc1/Dapper.SimpleCRUD#154]
Hi,

When querying within a transaction you can't call GetListAsync<T> with only a transaction parameter. It incorrectly maps the transaction to the "object whereConditions".

E.g.

await connection.GetListAsync<T>(Transaction)

Also you can't get around this by using "transaction: Transaction" as it complains about an argument mismatch.

E.g.

await connection.GetListAsync<T>(transaction: Transaction)

**Comment by ericdc1** [comment]
Interesting scenario. I would be interested in a pull request provided all tests still pass.
