### ISSUE TITLE
Supporting string based keys with custom property name in PostgreSQL

### ISSUE THREAD

**Issue by hussyd** [ericdc1/Dapper.SimpleCRUD#157]
Hi!

First of all thank you for this awesome extension! Really!

BUT :)

I noticed that when I insert an entity which has the following key property:
```
[Key]
[Required]
public string dpc_handle { get; set; }
```

then the Insert returns with an internal postgres id number which type is integer. The SimpleCRUD generates the following SQL commnad:
`INSERT INTO ...........; SELECT LASTVAL() AS Id`

I think the LASTVAL() is the problem. My workaround is a raw SQL insert that follows a _RETURNING <column_name_of_the_key>_, so:
`INSERT INTO ........... RETURNING dpc_handle;`

Can you please support this scenario also?

Thank you and all the best!

**Comment by ericdc1** [comment]
Thanks for the feedback. I don't postgres at all but I'd consider a pull request provided all tests still pass.
