### ISSUE TITLE
Table name truncated

### ISSUE THREAD

**Issue by ccrookston** [ericdc1/Dapper.SimpleCRUD#159]
The table `CurrentStatus` was generated as `CurrentStatu`.  

    /// <summary>
    /// A class which represents the CurrentStatus table.
    /// </summary>
	[Table("CurrentStatus")]
	public partial class CurrentStatu
	{
        ...
    }

I've not yet looked over the entire list of tables, but there may be others? I would assume this is some sort of setting in the template to make table names singular or plural, but I'm not finding it.

**Comment by ccrookston** [comment]
Ok, I found a way to fix this. It was indeed trying to singularize table names. I commented out line 518 of the template and added line 519:

//tbl.ClassName=Singularize(RemoveTablePrefixes(tbl.CleanName));
tbl.ClassName=RemoveTablePrefixes(tbl.CleanName);

Is there a better way?

**Comment by ericdc1** [comment]
Sure. You can tweak the schema for specific tables when the pluralizer doesn't make sense of things ending in an S. Check out around line 45. https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUD.ModelGenerator/Content/Models/ModelGenerator.tt.pp#L45

	tables["CurrentStatus"].ClassName = "CurrentStatus";
