### ISSUE TITLE
Insert does not support Guid key?

### ISSUE THREAD

**Issue by Meowzz95** [ericdc1/Dapper.SimpleCRUD#164]
As stated in doc, Guid keys are supported, but in my case, it failed to insert an entity with Guid as a primary key.

After look at the source code, it seems that this method
```
public static int? Insert<TEntity>(this IDbConnection connection, TEntity entityToInsert, IDbTransaction transaction = null, int? commandTimeout = null)
        {
            return Insert<int?, TEntity>(connection, entityToInsert, transaction, commandTimeout);
        }
```

does not even try to handle Guid as key...

**Comment by Meowzz95** [comment]
I've created a PR with a simple fix but this would break the inserted int ID.
[PR#165](https://github.com/ericdc1/Dapper.SimpleCRUD/pull/165)

**Comment by bossiep1** [comment]
I used var id = await conn.InsertAsync<Guid, T>(entity); and no issues

**Comment by ericdc1** [comment]
Here are the tests showing this working: https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L641
