### ISSUE TITLE
simpleCURD do not support string key

### ISSUE THREAD

**Issue by fengybl** [ericdc1/Dapper.SimpleCRUD#170]
![image](https://user-images.githubusercontent.com/18284232/44976106-bf0c2700-af96-11e8-9772-024bc9d137bf.png)
when my pojo key type is string this function will skip the key
actually i have already assigned value to the key
please fix it ths~

**Comment by fengybl** [comment]
![image](https://user-images.githubusercontent.com/18284232/44976612-52922780-af98-11e8-8e31-f17f18bb8eeb.png)
i add a condition a like this

**Comment by harryperales** [comment]
any updates on this?

**Comment by ericdc1** [comment]
this will be in the next release

**Comment by fengybl** [comment]
> this will be in the next release

thks
