### ISSUE TITLE
do not support [column] attribute

### ISSUE THREAD

**Issue by fengybl** [ericdc1/Dapper.SimpleCRUD#171]
when i add [column] attribute to the pojo it doesn't work

**Comment by ericdc1** [comment]
This is incorrect. See this documentation: https://github.com/ericdc1/Dapper.SimpleCRUD#attributes

and this test showing it working: https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L948
