### ISSUE TITLE
Option for SET IDENTITY_INSERT

### ISSUE THREAD

**Issue by RobSchripsema** [ericdc1/Dapper.SimpleCRUD#183]
I have a rather unusual scenario where I have a table with an autoincrement IDENTITY value coupled with a second column (a char(2), in this case) serving as  a Primary Key. In most cases, I want to insert records, specifying the char(2) column and letting SQL provide the new IDENTITY value. Works fine. 

Sometimes, however, I want to create a SECOND record with the same IDENTITY value, but a different char(2) value. Since the PrimaryKey is a composite of both, SQL allows this. I can do this in raw SQL by setting IDENTITY_INSERT ON/OFF for that table while inserting. 

Of course, my question/request is, is there a way to (currently) do this with Dapper (specifically your SimpleCRUD extensions)? If not, would you consider this an option -- essentially a way to generate the INSERT statement *including* the primary key and then setting IDENTITY_INSERT appropriately. I realize I can set the 'Required' attribute on the Key field, but then it is ALWAYS included, which I don't want in most cases.

Thoughts?

**Comment by jonathanlarouche** [comment]
I had the same issue in our project.
What I suggest is to create a separated class for Identity Inserts, that second class will inherit from.


Eg:
```
[Table("abc")]
public class Abc {
   [Key]
   public virtual int Id { get; set; }
   public virtual string CharValue {get; set; }
}

[Table("abc")]
public class AbcIdentityInsertable : Abc {
   [Key]
   [Required]
   public override int Id { get; set; }
}

```
When you need to Insert with Identity use the AbcIdentityInsertable class, otherwise use the base class.

Note that you will need to call Set Identity_Insert ON/OFF, 
I suggest that you create a function that will encapsulate this with the Insert, Something like this:
```

public static int InsertWithIdentity<T>(SqlConnection sqlConnection, T entity)
{
	string tableName = new SimpleCRUD.TableNameResolver().ResolveTableName(typeof(T));
	sqlConnection.Execute($"SET IDENTITY_INSERT {tableName} ON");

	int result = sqlConnection.Insert(entity);

	sqlConnection.Execute($"SET IDENTITY_INSERT {tableName} OFF");

	return result;
}
```

Thanks,
Jonathan

**Comment by RobSchripsema** [comment]
A great idea, Jonathan. I had pursued a similar path, though I hadn't thought of the inherited class idea.

We've since come up with a different data model, one that will work better for us and doesn't require the compound key. But I'll definitely put your idea into my "bag of tricks" for the future!

Regards,

Rob

**Comment by oghenez** [comment]
> I had the same issue in our project. What I suggest is to create a separated class for Identity Inserts, that second class will inherit from.
> 
> Eg:
> 
> ```
> [Table("abc")]
> public class Abc {
>    [Key]
>    public virtual int Id { get; set; }
>    public virtual string CharValue {get; set; }
> }
> 
> [Table("abc")]
> public class AbcIdentityInsertable : Abc {
>    [Key]
>    [Required]
>    public override int Id { get; set; }
> }
> ```
> 
> When you need to Insert with Identity use the AbcIdentityInsertable class, otherwise use the base class.
> 
> Note that you will need to call Set Identity_Insert ON/OFF, I suggest that you create a function that will encapsulate this with the Insert, Something like this:
> 
> ```
> 
> public static int InsertWithIdentity<T>(SqlConnection sqlConnection, T entity)
> {
> 	string tableName = new SimpleCRUD.TableNameResolver().ResolveTableName(typeof(T));
> 	sqlConnection.Execute($"SET IDENTITY_INSERT {tableName} ON");
> 
> 	int result = sqlConnection.Insert(entity);
> 
> 	sqlConnection.Execute($"SET IDENTITY_INSERT {tableName} OFF");
> 
> 	return result;
> }
> ```
> 
> Thanks, Jonathan

Nice solution, but we have a lot of classes and this method would make more work. will look for another solution

**Comment by oghenez** [comment]
> A great idea, Jonathan. I had pursued a similar path, though I hadn't thought of the inherited class idea.
> 
> We've since come up with a different data model, one that will work better for us and doesn't require the compound key. But I'll definitely put your idea into my "bag of tricks" for the future!
> 
> Regards,
> 
> Rob

can you share?
