### ISSUE TITLE
Custom SqlMapper.TypeHandler<T> Not working with Insert

### ISSUE THREAD

**Issue by benrick** [ericdc1/Dapper.SimpleCRUD#188]
I'm using Dapper.SimpleCRUD in my project, but my custom `SqlMapper.TypeHandler<LocalTime>` does not get called when I use the `InsertAsync` extension method. Not sure why that is the case, I can write custom `QueryAsync` and `ExecuteAsync` calls that use my handlers as expected.

Notice that I can bypass SimpleCRUD and it seems to work OK.

This succeeds by calling my `NodaTime.LocalTime` handler.

```
string sql = "INSERT INTO ScheduledStreams (ChannelId, DayOfWeek, LocalStartTime, LocalEndTime, TimeZoneId) Values (@ChannelId, @DayOfWeek, @LocalStartTime, @LocalEndTime, @TimeZoneId);SELECT CAST(SCOPE_IDENTITY()  AS BIGINT) AS [id];";

int? id = (await connection.QueryAsync(sql, stream)).First().Id;
```

This fails by not calling my `NodaTime.LocalTime` handler.

```
int? id = await connection.InsertAsync(stream);
```

https://github.com/DevChatter/DevStreams/pull/34/commits/92e679e878336336834b4ab814387ddfa1d2ca88

**Comment by benrick** [comment]
From the Docs:
> Complex types are not included in the insert statement - This keeps the List out of the insert even without the Editable attribute. You can include complex types if you decorate them with Editable(true). This is useful for enumerators.

Seems it's not just `Insert`, but also on the `Get`. I was able to use the attribute to get them included. Please ignore this. Might be worth a note in the docs.

**Comment by benrick** [comment]
Found how that data can be looked up in Dapper.

```
DbType dbType1 = SqlMapper.LookupDbType(typeof(LocalTime), nameof(LocalTime), 
    false, out SqlMapper.ITypeHandler handler1); // our handler
DbType dbType2 = SqlMapper.LookupDbType(typeof(LocalDate), nameof(LocalDate), 
    false, out SqlMapper.ITypeHandler handler2); // null handler
DbType dbType3 = SqlMapper.LookupDbType(typeof(DateTime), nameof(DateTime), 
    false, out SqlMapper.ITypeHandler handler3); // null handler
```

Essentially, this method can be called while building up the select, insert, update, etc. list of fields. If SimpleCRUD were going to skip the type for not being simple, it could check to see if the developer included a custom TypeHandler. It will only find one if someone had explicitly included it in Dapper.

Up to you if you want to do something with this, but it would make it so that Custom Type Handlers worked with Dapper.SimpleCRUD.

**Comment by Ashtonian** [comment]
had to add it for the select as well.
