### ISSUE TITLE
GetListAsync<Task<T>>(conditions, transaction) doesn't work ONLY on 2.1.0

### ISSUE THREAD

**Issue by coderabsolute** [ericdc1/Dapper.SimpleCRUD#190]
My code works well with the **GetList** but GetListAsync is throwing the following error.

_One or more errors occurred. (You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '1` where `TenantId` = @TenantId and `productCategoryName` = @productCategoryName' at line 1)_

Any idea what could be wrong? Please be noted the same code works on `v2.0.1` but doesn't work as soon as I update to `v2.1.0`.

**Comment by ericdc1** [comment]
Hello - it seems to pass this test. https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L838

Are you able to provide a test that fails so I can debug?
