### ISSUE TITLE
Using Database Time With Insert And Update

### ISSUE THREAD

**Issue by ahmetkocadogan** [ericdc1/Dapper.SimpleCRUD#191]
I have InsertedDate property within my class. When i insert a recort, or update a record, is it possible to use database date and time with getdate() ?

May be like

```
  /// <summary>
    /// Optional UseDbTime attribute.
    /// Custom for Dapper.SimpleCRUD to use Database Time with Insert and Update methods
    /// </summary>
    [AttributeUsage(AttributeTargets.Property)]
    public class UseDbTimeAttribute : Attribute
    {
    }
```

and while generation raw sql, if attribute of DateTime typed property is UseDbTime, write getdate(). 

Is it possible ?

**Comment by ericdc1** [comment]
Not at this time with SimpleCrud.

You could use straight Dapper though:

     conn.Execute("update YourTable set SomeDate = GETDATE()");
