### ISSUE TITLE
How to dynamic IgnoreSelect in GetList()

### ISSUE THREAD

**Issue by oppoic** [ericdc1/Dapper.SimpleCRUD#192]
After reading the document, i found the IgnoreSelect attributes can remove Field from the select statement, but how to reomve Fields Dynamic? Maybe like this:

`
conn.GetList<Users>(new IgnoreField { Name, Email });
`

**Comment by ericdc1** [comment]
At this point why wouldn't you just use straight Dapper? https://github.com/StackExchange/Dapper 

      var person = connection.Query<User>("Select Name, Age from [User] where Id = @Id", new { Id = 1 });

I feel that if you are getting into untyped strings you are really outside the scope of Dapper SimpleCRUD.

Typically, I'd recommend making a "viewmodel" with the limited number of fields and use that in the places you want to work with a limited fieldset.


     namespace YourApp.ViewModels
     {
         public class UserMinimalViewModel
         {
             [Required, MaxLength(50)]
             [Display(Name = "Name")]
             public string Name { get; set; }

             public int Age { get; set; }
         }
    }

Then you could simply do this and avoid the magic strings. 
    
     var user = connection.Get<UserMinimalViewModel>(1}); 

Eric
