### ISSUE TITLE
[NotMapped] not working

### ISSUE THREAD

**Issue by Calx-Takeno** [ericdc1/Dapper.SimpleCRUD#195]
I find this.

namespace Dapper
{
    //
    //     Optional NotMapped attribute. You can use the System.ComponentModel.DataAnnotations
    //     version in its place to specify that the property is not mapped
    [AttributeUsage(AttributeTargets.Property)]
    public class NotMappedAttribute : Attribute
    {
        public NotMappedAttribute();
    }
}

but

System.ComponentModel.DataAnnotations.Schema.NotMappedAttribute

not working

**Comment by ericdc1** [comment]
This test is passing. - https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L445 

Do you have a test showing it not working?
