### ISSUE TITLE
Where's the Example Website for T4 Template?

### ISSUE THREAD

**Issue by prindacerk** [ericdc1/Dapper.SimpleCRUD#196]
I am trying to figure out where the "T4 Template" sample website project mentioned in the wiki page here.
https://github.com/ericdc1/Dapper.SimpleCRUD/wiki/T4-Template

Reason I am looking for the sample website is to see how the Nuget package for the ModelGenerator is used. If I copy the .tt.pp file manually and run it within my project, it seems to work fine. But I cannot figure out how the Nuget package comes into play. Installing the nuget package did nothing.

Please kindly advise. Should I just use the template file instead of the nuget package?

**Comment by ericdc1** [comment]
Hello,

Sorry about that. When updating to .Net Core I deleted the website project and planned on redoing it in Core but never did.

The nuget package really just copies the .tt.pp file into your Models directory and makes the namespaces match your project. Simply copying the .tt.pp file and manually editing the namespace would work just as well.
