### ISSUE TITLE
T4 Template Generation doesn't seem to work with custom Column datatype

### ISSUE THREAD

**Issue by prindacerk** [ericdc1/Dapper.SimpleCRUD#197]
I have a sql column datatype as datetimeoffset which was linked to my class structure DateTimeOffset. But this isn't available in the template so I tried to apply custom type for the column. 
But the template threw error because it doesn't accept the code
`tables["tablename"]["columnname"].PropertyType="bool";`

This is not valid for the template. Can you please advice?

**Comment by ericdc1** [comment]
I am not sure as I use this in my T4 extensively.

	tables["tablename"]["columnname"].PropertyType="mytype";

I suspect something else is wrong in your T4.

**Comment by prindacerk** [comment]
I found the alternative way to get this working. By adding the datetimeoffset mapping to the GetPropertyType method in the template.
