### ISSUE TITLE
Doesn't support array list parameters

### ISSUE THREAD

**Issue by Calx-Takeno** [ericdc1/Dapper.SimpleCRUD#201]
public static IEnumerable<T> GetList<T>(this IDbConnection connection, object whereConditions, IDbTransaction transaction = null, int? commandTimeout = null)

SimpleCRUD generated wrong SQL syntax.

Sample Code Like:

List<int> idList=new List<int>(){1,2};
GetList<xxx>(new {id=idList});

It will generated SQl like this from SQL SERVER Profiler

exec sp_executesql N'Select id from [xxx] where [id] = (@aid1,@aid2)',N'@id1 int,@id2 int',@id1=1,@id2=2

But this is wrong SQL syntax
It should be 'Where [id] in (@aid1,@aid2)' , it should not be '='

I'm using SimpleCURD lastest code.

**Comment by ericdc1** [comment]
You are right that this doesn't work. It is outside the intent of "Simple" CRUD. In this case, I'd use straight Dapper and write my own SQL statement. SimpleCRUD is intended to help with the routine CRUD stuff but when you get into more complex stuff like this you should use Dapper or something else.
