### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by kiquenet** [ericdc1/Dapper.SimpleCRUD#202]
revisions for T4 Template ?

The only cautionary note is that, since it's all async, if your service or app starts getting hit too hard (this depends on your server architecture and resources), it may start returning HTTP 503 responses. So, you may need a throttler or a request queue or something. That's not something I've tackled yet, but maybe 
I'll do a future post about that.
https://www.joesauve.com/async-dapper-and-async-sql-connection-management/

Dapper and SPs
https://itsmebhavin.wordpress.com/2015/11/19/dapper-net-and-dapperextensions-to-run-stored-procedures/

Cancel and Dapper
https://stackoverflow.com/questions/25540793/cancellationtoken-with-async-dapper-methods

**Comment by ericdc1** [comment]
Noted
