### ISSUE TITLE
Why is [key] required in GetList?

### ISSUE THREAD

**Issue by mariusGundersen** [ericdc1/Dapper.SimpleCRUD#204]
[There is a check](https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUD/SimpleCRUD.cs#L189) that the table class has either an `Id` property or a property marked with `[Key]`, but why is that? It's not used for anything in the method.

**Comment by ericdc1** [comment]
Good call. That is a bug. It will be fixed in the next version.

**Comment by rmp135** [comment]
This check is also in the GetListAsync methods where it isn't used either.
