### ISSUE TITLE
Generate POCOs in Class Library

### ISSUE THREAD

**Issue by DenZuck** [ericdc1/Dapper.SimpleCRUD#206]
I need to generate my POCOs in a class library but I don't know what to do.

I have copied ModelGenerator.tt in my Class Library but POCOs generation fails. Do I have to set some parameters in ModelGenerator to specify where the connection string is ? Class library does not have App.config where the connection string is normally stored.

Or do I have to copy ModelGenerator.tt in my application and set a parameter that specify where the POCOs have to be generated ?

**Comment by ericdc1** [comment]
You need to create an app.config with a valid connection string or use a relative path to the connection string in another project like this:

       ConnectionStringName = "MyConnectionString"; // Uses last connection string in config if not specified
       ConfigPath = @"../../My.Website/web.config"; //Looks in current project for web.config or app.config by default. This overrides to a relative path - useful for seperate class library projects.
