### ISSUE TITLE
Nullable fields are not inserted with version >= 2.1.0 while this works with 1.13.0

### ISSUE THREAD

**Issue by wkosten1982** [ericdc1/Dapper.SimpleCRUD#209]
After upgrading version 1.13.0 to 2.1.0 I discovered a problem inserting values of nullable fields. After executing the Insert command the values in the table are all NULL except for the properties that are not nullable. After rolling back the package version to 1.13.0 it works again.

Do I need to add some attributes to my nullable properties or is this a bug?

**Comment by ericdc1** [comment]
Would you be willing to submit a unit test or sample code showing this?
