### ISSUE TITLE
Support for Dapper >= 2.0

### ISSUE THREAD

**Issue by istrupin** [ericdc1/Dapper.SimpleCRUD#213]
Hello,

I was curious whether there was planning on supporting Dapper 2.0.0+.  The .nuspec currently lists Dapper (>= 1.50.5 && < 2.0.0) as dependencies.

I'd be happy top help in any way.

**Comment by istrupin** [comment]
I've made an attempt here:
https://github.com/istrupin/Dapper.SimpleCRUD/tree/dapper2.0-support

I'm happy to send you a PR if you'd like (just let me know what branch you'd like the PR to).

Note that this attempt does drop support for 452 though (because Dapper drops this support as well).

**Comment by ericdc1** [comment]
Please submit it - I'd prefer one rebased commit to make it easier to understand. Do all tests pass?

**Comment by istrupin** [comment]
All tests for SqlServer (Sql Express) do indeed pass.  I don't have postgres or anything else available readily available though.

I'll send you a squashed PR to master today.  One thing to note -- I made a best attempt to get the .nuspec file updated correctly as well, but to be completely honestly with you, getting the nuget packaging set up is not really my forte.  I couldn't even get the one in the master branch to work.

If you do end up having to modify it additionally, I'd love to see what all that involves.

**Comment by istrupin** [comment]
Managed to figure out how to get nuget packaging to work .  It does seem to create a nupkg file.

**Comment by mikrj** [comment]
@ericdc1 @istrupin is this ready for being merged? We would love to to have support for Dapper 2.0.0.

Let me know if there is anything I can assist with.

**Comment by istrupin** [comment]
> @ericdc1 @istrupin is this ready for being merged? We would love to to have support for Dapper 2.0.0.
> 
> Let me know if there is anything I can assist with.

Testing on my end looked good! -- I believe @ericdc1  is just doing the final batch of testing,
