### ISSUE TITLE
 “Dapper.SimpleCRUD.SetDialect” How do I use it when a project with multiple types of databases?

### ISSUE THREAD

**Issue by aqa365** [ericdc1/Dapper.SimpleCRUD#218]
"Dapper.SimpleCRUD.SetDialect(Dapper.SimpleCRUD.Dialect.MySQL)"
How do I use it when a project with multiple types of databases? (sqlserver,mysql)

**Comment by coderabsolute** [comment]
I think you should be able to create a wrapper for each of the databases you are trying to use. And, in that wrapper, you can mention the `SetDialetct`?

**Comment by praczhen** [comment]
> 我认为您应该能够为要使用的每个数据库创建一个包装器。并且，在该包装中，您可以提及`SetDialetct`？

"SetDialetct" is static....   it is not thread safe

**Comment by lezhkin11** [comment]
> I think you should be able to create a wrapper for each of the databases you are trying to use. And, in that wrapper, you can mention the `SetDialect`?

Unfortunately, this is not thread-safe.

**Comment by ericdc1** [comment]
Sorry but this usecase is beyond the intent of simplecrud. I would consider a PR that solves this if it isn't too far reaching
