### ISSUE TITLE
How to deal with postgresql geometry?can show demo thanks

### ISSUE THREAD

**Issue by allycs** [ericdc1/Dapper.SimpleCRUD#220]
The member Geometrys of type Npgsql.LegacyPostgis.PostgisGeometry cannot be used as a parameter value.
How to deal with postgresql geometry?can show demo thanks

**Comment by ericdc1** [comment]
I personally don't use Postgres. I am willing to consider PRs to extend this for Postgres but it isn't something I am interested in doing myself.
