### ISSUE TITLE
Nuspec is pointing at an invalid version for 2.0

### ISSUE THREAD

**Issue by TangoMikeOscar** [ericdc1/Dapper.SimpleCRUD#223]
Our build is full of warnings because the nuspec is pointing at dapper version `2.0`  which does not exist (whether it was deleted, I do not know).

I've submitted a pull request to fix this. Hopefully this is acceptable.

Pull Request: #222

**Comment by ericdc1** [comment]
Fixed by referencing 2.x. thanks!

**Comment by TangoMikeOscar** [comment]
@ericdc1 Has this fix actually been pushed out to nuget? Version 2.2.0.1 still has this issue.

**Comment by fuglede** [comment]
I also ran into this just now on 2.2.0.1 while using Dapper 2.0.78:

![image](https://user-images.githubusercontent.com/6169306/110750286-8b36aa00-8242-11eb-9af0-bc72fc68a77d.png)

> warning NU1603: Dapper.SimpleCRUD 2.2.0.1 depends on Dapper (>= 2.0.0) but Dapper 2.0.0 was not found. An approximate best match of Dapper 2.0.4 was resolved.
