### ISSUE TITLE
function InsertAsync<uint, TEntity>(entity, m_transaction, m_commandTimeout) return 0

### ISSUE THREAD

**Issue by neil-he** [ericdc1/Dapper.SimpleCRUD#224]
I lookup the SimpleCRUDAsync.cs file, find the InsertAsync<TKey, TEntity> funtion have a condition like this:
 if ((keytype == typeof(int) || keytype == typeof(long)) && Convert.ToInt64(idProps.First().GetValue(entityToInsert, null)) == 0)
            {
                sb.Append(";" + _getIdentitySql);
            }
I think it does not include TKey==uint condition.

**Comment by ericdc1** [comment]
Please provide some test code to show there is a problem in this method.
