### ISSUE TITLE
function BuildInsertValues and BuildInsertParameters 

### ISSUE THREAD

**Issue by xiangnanxiao** [ericdc1/Dapper.SimpleCRUD#226]
Line 809, only the Guid is filtered. advice add String

if (property.Name.Equals("Id", StringComparison.OrdinalIgnoreCase) &&
                    property.GetCustomAttributes(true).All(attr => attr.GetType().Name != typeof(RequiredAttribute).Name) &&
                    property.PropertyType != typeof(Guid) &&
                    property.PropertyType != typeof(String))

**Comment by ericdc1** [comment]
Please provide some test code to show there is a problem in this method.
