### ISSUE TITLE
InsertAsync<int, Child>(newChild) throws exception: System.Data.SqlClient.SqlException (0x80131904): An object or column name is missing or empty

### ISSUE THREAD

**Issue by rcholic** [ericdc1/Dapper.SimpleCRUD#229]
I got two classes with 1 - many relations between parent and its children:

```c#
public class Parent {
  public int Id {get; set;}
  public string Name {get; set;}
  public List<Child> Children {get; set;}
}

// a parent may have many children
public class Child {
  public int Id {get; set;}
  public int Age {get; set;}
  public Parent MyParent {get; set;}
 public int MyParentId {get; set;}
}
```

I need to insert a child for a given parent id, so I used the `InsertAsync<int, Child>(newChild)` method to do the insert:

```c#
using (IDbConnection connection = new SqlConnection(this.connectionString))
{
          return await connection.InsertAsync<int, Child>(newChild);
}
```

But this throws exception:

>System.Data.SqlClient.SqlException (0x80131904): An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.

I added a breakpoint before the InsertAsync execution, and I saw none of the fields of the newChild object were missing. So I dont understand what column name is missing or empty in the exception. Anyone has seen similar errors?

**Comment by ccrookston** [comment]
I am seeing the same error. Did you find a solution?

**Comment by ccrookston** [comment]
I found a solution to my issue:
https://github.com/ericdc1/Dapper.SimpleCRUD/issues/242

**Comment by ericdc1** [comment]
left comment on 242
