### ISSUE TITLE
关于使用InsertAsync时存在的异常

### ISSUE THREAD

**Issue by liuww111** [ericdc1/Dapper.SimpleCRUD#232]
环境是Core3.1 MVC，当我使用InsertAsync插入的时候，我发现多次执行后只插入了一行数据，导致我最近的日志记录出现了问题，代码如下
`var cs = Configs.AppSettings["MS"];
            using (var connection = new SqlConnection(cs))
            {
                var log = new DDReportLog() { AccessTime = DateTime.Now, UrlPath = "Test", Userid = "Test", Nick = "Test" };
                //connection.InsertAsync<DDReportLog>(log);
                connection.Insert(log);
            }`
如使用Insert则插入正常

**Comment by ericdc1** [comment]
Sorry, I do not know Chinese
