### ISSUE TITLE
“SimpleCRUD.SetDialect” How do I use it when a project with sqlserver and mysql

### ISSUE THREAD

**Issue by agoling** [ericdc1/Dapper.SimpleCRUD#233]
“SimpleCRUD.SetDialect” How do I use it when a project with sqlserver and mysql

**Comment by agoling** [comment]
![image](https://user-images.githubusercontent.com/37896493/87019283-fee06d00-c204-11ea-9f32-7fa51352fcee.png)
If multiple databases are used, the string will be replaced

**Comment by ericdc1** [comment]
There isn't support to use multiple database dialects at the same time
