### ISSUE TITLE
查询视图

### ISSUE THREAD

**Issue by zyh1988** [ericdc1/Dapper.SimpleCRUD#234]
is:issue is:open SimpleCRUD 怎么查询视图，正常的MySQL 查询视图语句，执行的时候 报“语法错误”

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'select * from v_itemapp_caseinfo Order By id LIMIT 0,20' at line 1

用Conn.Query 没有问题，使用Conn.GetListPaged 出现上述问题

**Comment by ericdc1** [comment]
Sorry, I cannot read Chinese
