### ISSUE TITLE
Insert list of entity

### ISSUE THREAD

**Issue by senterol** [ericdc1/Dapper.SimpleCRUD#235]
Hi everyone,

Im actualy using Dapper.SimpleCRUD for build my own project but, i still have a problem...

When i try to insert a list of enity i recive always this error:

[23:21:33][ERROR][Insert]: Specified cast is not valid.
System.InvalidCastException: Specified cast is not valid.
   at Dapper.SimpleCRUD.Insert[TKey,TEntity](IDbConnection connection, TEntity entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout)

Actualy, my insert is like:

foreach (Entity entity in entityList)
{
      connection.Insert(entity);
}

I try to Disable virtual class, remove it from mapping, remove read and all the other options but i still receive this error.

The only way that i have to put this data is with a manual insert:

connection.Insert(new Entity { values ~ } );

**Comment by ericdc1** [comment]
Please provide some test code to show there is a problem in this method.
