### ISSUE TITLE
Bug on Get for Custom table/column name resolvers

### ISSUE THREAD

**Issue by BeyondMySouls** [ericdc1/Dapper.SimpleCRUD#236]
When using Custom table/column name resolvers, column names are not resolved back for Get() methods. Mapping is done only when sent, but not on retrieval.

E.g. `connection.GetList<Person>(new { CountryCode = "USA" });`

When sending, CountryCode is resolved to country_code, but when retrieve the column country_code is not mapped back to CountryCode. Hence, CountryCode will have a null value.

**Comment by ericdc1** [comment]
Please provide some test code to show there is a problem in this method and I'd be glad to look into it deeper.
