### ISSUE TITLE
Sqlite Insert<TEntities> Bug

### ISSUE THREAD

**Issue by fengybl** [ericdc1/Dapper.SimpleCRUD#237]
my entities have [Key] attribute and also named Id
but when i use inset<TEntities> function it throw this exception as follow:
Insert<T> only supports an entity with a [Key] or Id property”
![image](https://user-images.githubusercontent.com/18284232/94234958-4d1c2700-ff3d-11ea-8ee0-ba949afab984.png)

**Comment by ericdc1** [comment]
Please provide some test code to show there is a problem in this method.
