### ISSUE TITLE
Get DateTime from SQLite, Convertion Error

### ISSUE THREAD

**Issue by PatrickRainer** [ericdc1/Dapper.SimpleCRUD#240]
Dear all

I am unsure if I am doing something wrong, or if it is a bug. I am using SqLite and setup up the dialect of Simple Crud to it. When I try to get data from a table which has DateTime values saved as "Int64", like SqLite does, I get a convertion Error.

Inserting to the table works fine.

**Here is the Error:**

`System.Data.DataException : Error parsing column 3 (StartDateTime=2024 - Int64)
  ----> System.InvalidCastException : Ungültige Umwandlung von "Int64" in "DateTime".
   bei Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in C:\projects\dapper\Dapper\SqlMapper.cs:Zeile 3633.
   bei Deserialize7ed4c0e0-0a90-4067-89f7-3feb0349a1dd(IDataReader )
   bei Dapper.SqlMapper.<QueryImpl>d__140`1.MoveNext() in C:\projects\dapper\Dapper\SqlMapper.cs:Zeile 1098.`

**The model looks like that:**

>    public class Execution : IModel
>     {
>         [Key] public int ExecutionId { get; set; }
>         [Required] public string Course { get; set; }
>         [Required] public string Employee { get; set; }
>         public DateTime StartDateTime { get; set; }
>         public DateTime EndDateTime { get; set; }
>     }

**The method to get data:**

> public void GetExecutionSingle()
>         {
>             var record = _conn.Get<Execution>(11);
>             Assert.NotNull(record);
>         }

Any hints?

**Comment by ericdc1** [comment]
Please provide some test code to show there is a problem in this method. There is a test project where you can write this.
