### ISSUE TITLE
Attribute for selective inclusion of columns in insert/update

### ISSUE THREAD

**Issue by aiernt** [ericdc1/Dapper.SimpleCRUD#263]
I know you can tag class properties for ignore, readonly, editable, etc. Have you ever thought about selective inclusion? If I have a class with properties and a handful are required, the rest are optional (meaning nullable). If there was an attribute used (maybe [InsertSelective] or [UpdateSelective]), where for each property tagged if it was null it was not included, but if it was not null then it included the property in the insert/update. 

Can this be done currently? I might have missed it. 

This would be extremely helpful. We have tons of code where we are looking at class properties, checking null and selectively including them in the list of db properties being sent down to a stored procedure.  The TLDR; is to use the SQL server default constraints unless the property was populated with a value.

**Comment by ericdc1** [comment]
Have you looked at [Editable(false)]

By default the insert statement would include all properties in the class - The Editable(false), ReadOnly(true), and IgnoreInsert attributes remove items from the insert statement
Properties decorated with ReadOnly(true) are only used for selects
Complex types are not included in the insert statement - This keeps the List out of the insert even without the Editable attribute. You can include complex types if you decorate them with Editable(true). This is useful for enumerators.
