### ISSUE TITLE
Question: A primary key that is not identity.

### ISSUE THREAD

**Issue by iannicktl** [ericdc1/Dapper.SimpleCRUD#271]
I'm not sure if I can't figure out what to do. 
Or maybe this library doesn't support insert with a primary key that is not identity (and not a guid)?

Dapper.Contrib has a [ExplicitKey] for this case. But its lacking some feature that this library has.

**Comment by REDECODE** [comment]
Hello, you can do this using Required on the same property of the Key.

> [Required] - By default the [Key] property is not inserted as it is expected to be an autoincremented by the database. You can mark a property as a [Key] and [Required] if you want to specify the value yourself during the insert.
