### ISSUE TITLE
Can't insert records in a table N-N (without Id)

### ISSUE THREAD

**Issue by asanoguera** [ericdc1/Dapper.SimpleCRUD#28]
When try to insert a record in a table N-N (formed by 2 foreign keys, but non primary key) the Insert method show the legend 'Insert<T> only supports an entity with a [Key] or Id property' (which is correct) and kick-out. 
But in this case I don't need get any Id in return, so, I think that can help for tables which don't have any primary key an Insert method that not return any Id, and don't stop. I see a branch 'keylessinsert' but seems old.
In fact a new method Insert without any return will be extremely tiny, just:

```c#
public static void Insert(this IDbConnection connection, object entityToInsert, IDbTransaction transaction = null, int? commandTimeout = null)
{
    var name = GetTableName(entityToInsert);
    var sb = new StringBuilder();
    sb.AppendFormat("insert into {0}", name);
    sb.Append(" (");
    BuildInsertParameters(entityToInsert, sb);
    sb.Append(") ");
    sb.Append("values");
    sb.Append(" (");
    BuildInsertValues(entityToInsert, sb);
    sb.Append(")");

    var r = connection.Query(sb.ToString(), entityToInsert, transaction, true, commandTimeout);
}
```

Do you think in the future add some like that?

The SimpleCRUD is extremely useful, thanks and congratulations!

**Comment by ericdc1** [comment]
If there is any additional interest I this I would consider adding it.

**Comment by chrishylton** [comment]
I would use this, actually doing something very similar to what asanoguera is doing above.  I'd further add to this that it'd be nice to see this ability in 'batch' as well, like writing to a logging table.  Basically Insert(List<T> objects), with or without a key, but batch up the statements and have it chunk them up in one pass to the database.

**Comment by YogirajA** [comment]
This can be a useful feature. I can try implementing this.

**Comment by YogirajA** [comment]
I implemented this and tested it. You can take a look at [my feature branch](https://github.com/YogirajA/Dapper.SimpleCRUD/tree/feature/AssociativeInsert) for the implementation. However, I dont' think this feature is worth the effort. It felt like a superfluous one. I'd rather use plain old SQL with Dapper for these types of operations. It also has an effect on Delete which is again not very necessary. I'd vote to keep this out at this time to maintain SimpleCRUD as it says Simple :) 

@chrishylton  For the batch SQL, that's not very hard either,is it? You can either make use of transactions and commit after all the inserts are done or create a SQL with a bunch of SQL inserts in it (used it in past..works well)  or use Dapper like below:

       connection.Execute(@"insert MyTable(colA, colB) values (@a, @b)",
       new[] { new { a=1, b=1 }, new { a=2, b=2 }, new { a=3, b=3 } }).IsEqualTo(3); 
      // 3 rows inserted:   "1,1", "2,2" and "3,3"

This extension doesn't need to support this again.

These are just my opinions after I wrote some code for it. @ericdc1 thoughts?

**Comment by ericdc1** [comment]
I completely agree @YogirajA. This and a few other proposed features (such as Upsert) are beyond the concept of "simple" and really should just be written as plain SQL with Dapper. Thanks for the feedback.
