### ISSUE TITLE
Not able to update using sqlite

### ISSUE THREAD

**Issue by sandeshmm** [ericdc1/Dapper.SimpleCRUD#29]
Not able to update the sqlite table using below command

 SQLiteConnection connection = new SQLiteConnection(conn);
  var user = connection.Get<Users>(36);
                user.EmailID = "sandesh@xyz.com";
                connection.Update(user);

throwing the error 
Error	1	The event 'System.Data.SQLite.SQLiteConnection.Update' can only appear on the left hand side of += or -=	C:\Users\SG2057\documents\visual studio 2012\Projects\TestSQLIte\TestSQLIte\Program.cs	24	28	TestSQLIte

Please note:  if I use below then works fine
 DbConnection connection = new SQLiteConnection(conn);

**Comment by ericdc1** [comment]
I couldn't replicate this with update but insert wasn't working with SQLite. I added support for SQLlite using the SetDialect method. It generates proper insert statements to return the primary key. The unit tests now test against SQLite. See https://github.com/ericdc1/Dapper.SimpleCRUD/commit/9193316a75606c2dc4caeb7cff7e82c4620a7dd4 

     SimpleCRUD.SetDialect(SimpleCRUD.Dialect.SQLite);

**Comment by sandeshmm** [comment]
One more thing i observed is, SQLiteConnection object  has built in Update method so there is a conflict between framework update and sqliteConnection update method so it is throwing the error.  If we uses the DBConnection then it does't have update method so working fine. 

It is nice plug in thank you very much. 

Thanks.
