### ISSUE TITLE
Bug with WHERE clause in Get method?

### ISSUE THREAD

**Issue by krate2000** [ericdc1/Dapper.SimpleCRUD#32]
Great software - just what I was looking for.

I think I've found a bug though:

In the Get method, when creating the WHERE clause onlyKey.name is used which returns the property name not taking into account that the property might have a Column attribute. Should this instead be: GetColumnName(onlyKey)?

**Comment by krate2000** [comment]
This also appears to be an issue in the delete method

**Comment by ericdc1** [comment]
Fixed in version 1.8.4. Thanks
