### ISSUE TITLE
Editable(false) Attribute stops data being selected

### ISSUE THREAD

**Issue by ericej1** [ericdc1/Dapper.SimpleCRUD#35]
I recently updated from an older version, not sure which one, but is this by design to have the Editable(false) attribute prevent the property from being read on the Get?  

I have fields such as CreatedDateTime, ModifedDateTime, etc, that I use default value / triggers on the database creating the values which I marked as Editable(false).  That way it doesn't attempt to insert or update these fields as I want the DB to manage them.  However, when a select is run from any of the Gets the function GetScaffoldableProperties strips out anything with Editable(false) on it so the never gets filled.

As a workaround I created a new function for the selects that wouldn't parse out the Editable(false) properties for the Gets and I was thinking about adding a new attribute to make it a big cleaner and controllable.  Thoughts?

**Comment by ericdc1** [comment]
This was an unintended consequence of the new column attribute feature where you can have custom property names and define the true database column name with an attribute. For this to work, we can't "select * from" anymore as the select needs to alias the column to the field name so mapping can work properly.

For example: 
[Column("strName")]
public string FullName {get;set;}

makes a select like this: "select strName as FullName from table"

I don't see any relevant attributes in dataannotations but I would consider adding something specific to SimpleCRUD.  https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations(v=vs.110).aspx

Maybe we need something like a custom [SelectColumn] attribute? I wonder if its better to just have a different model class for inserts and updates than for selects - in other words, are we making it worse or better by adding another attribute. 

Thanks for noticing this and pointing it out.

**Comment by ericej1** [comment]
I'm not sure i like having to decorate 2 attributes for what is basically a Read Only field.  Maybe extend out [Editable(false,AllowSelect=true)] or something?

What I ended up doing temporarily is this:

        private static IEnumerable<PropertyInfo> GetScaffoldableProperties_Select(object entity)
        {
            var props = entity.GetType().GetProperties();
            return props.Where(p => p.PropertyType.IsSimpleType());
        }
Then I replaced it in the each of the Gets.  I've been debating how to fix it permanently in my solution which is why I decided to post here as I dug through it seemed unintended.

**Comment by ericdc1** [comment]
i think this is what we need. https://msdn.microsoft.com/en-us/library/system.componentmodel.readonlyattribute%28v=vs.110%29.aspx 

Instead of using [Editable(false)] on those columns you could use [ReadOnly(true)]

If that makes sense I will get it added.

**Comment by ericej1** [comment]
I was actually about to mention that one.  Yes I think that makes good sense and would be easier to implement coded wise.

**Comment by ericdc1** [comment]
This has been implemented and is available both on Github and on Nuget. Let me know if you have any problems.
