### ISSUE TITLE
Why is default insert functionality not working?

### ISSUE THREAD

**Issue by Jabberrwocky** [ericdc1/Dapper.SimpleCRUD#36]
Hi,

Here is a sample of my schema:

[System.ComponentModel.DataAnnotations.Schema.Table("tblUsers")]
    public partial class User
    {
        [Key]
        public virtual long ID { get; set; }
        public virtual string Title { get; set; }
        public virtual string Name { get; set; }
        public virtual string Email { get; set; }
        public virtual string Username { get; set; }
        public virtual string Phone { get; set; }
        ...

I am trying to do this, per the documentation:

    _connection.Insert<User>(user);

However, I get this error message:

"Message":"An error has occurred.","ExceptionMessage":"Invalid return type","ExceptionType":"System.Exception","StackTrace":" at Dapper.SimpleCRUD.Insert[TKey](IDbConnection connection, Object entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) in c:\\_Code\\ThirdParty\\Dapper.SimpleCRUD\\Dapper.SimpleCRUD\\SimpleCRUD.cs:line 232\r\n at VIPAthlete.API.Models.UserManager.Insert(User user) in c:\\_Code\\VIPAthlete-Web\\VIPAthlete.API\\Models\\User.cs:line 102\r\n at VIPAthlete.API.Controllers.UsersController.Post(User user) in c:\\_Code\\VIPAthlete-Web\\VIPAthlete.API\\Controllers\\UsersController.cs:line 75"

Doing some digging into the source code, I see this at SimpleCRUD.cs:line 232: 

    var baseType = typeof(TKey);
    var underlyingType = Nullable.GetUnderlyingType(baseType);
    var keytype = underlyingType ?? baseType;

In my case, baseType turns out to be "User" and not the Key (which is ID, a 'long' type).

This does solve my problem and works fine:

    _connection.Insert<long>(user);

Why doesn't my initial insert line of code work?

Thanks.

**Comment by ericdc1** [comment]
Hello,

I had the documentation incorrect for insert. The insert method only returns the primary key not the whole object. 

Here are some examples:
 - returns INT primary key 
var id = connection.Insert(new User { Name = "User1", Age = 10 });

-returns GUID primary key
           var id = connection.Insert<Guid>(new GUIDTest { Name = "InsertIntoTableWithGuidKey", Guid = guid });

To get the whole object you could do something like this: 

                var user = new User {Name = "User1", Age = 10};
                var newId = connection.Insert(user);
                user.Id = newId.Value;
                return user;

**Comment by Jabberrwocky** [comment]
Thank you for the clarification and updating the documentation. Really appreciate your hard work.
