### ISSUE TITLE
Have a DeleteList

### ISSUE THREAD

**Issue by RufusJWB** [ericdc1/Dapper.SimpleCRUD#42]
It would be great to have a DeleteList method with a signature comparable to the GetList method:

    public static int DeleteList <T>(this IDbConnection connection, object whereConditions)

**Comment by ericdc1** [comment]
Good suggestion. I needed this just now. I will add this soon.

**Comment by ericdc1** [comment]
This is implemented and available as a prerelease nuget package at https://www.nuget.org/packages/Dapper.SimpleCRUD/1.9.0-beta 

I added documentation to the github project page, unit tests, and a working example in the included sample website (users page). 

If you have any comments or suggestions please let me know.

**Comment by RufusJWB** [comment]
Thank you! It's highly appreciated!
