### ISSUE TITLE
Helper method to avoid SQL injection

### ISSUE THREAD

**Issue by mauroandrea** [ericdc1/Dapper.SimpleCRUD#44]
Hi all!

Thanks for such a great project!

I was working with some POCs and I found that there's a helper missing that could help a lot. The problem was when I was trying to do a select with a like condition.

I know that you already mentioned in the documentation that for using >< and like we should use Dapper's query, but honestly if I go in that way I'll lost all the mappings...

Here's my scenario:
var orgs = connection.GetList<Organization>("where name like '%" + name + "%'");

As you can imagine this is impossible to use because it's open to SQL injection, so instead of doing that I needed to do the following:

var orgs = connection.Query<Organization>("select * from organizations where name like @Name", new {Name = "'%" + name + "%'"});

But once again, the problem is that I lost all the mappings I created with SimpleCRUD.

So, to fix this situation I needed something like this:

var orgs = connection.GetList<Organization>("where name like @Name", new {Name = "%" + name + "%"});

And because of that I downloaded the SimpleCRUD file and I added my own method. If you think that's helpful and it can be included, be my guest.

Regards.

Mauro

        /// <summary>
        /// <para>By default queries the table matching the class name</para>
        /// <para>-Table name can be overridden by adding an attribute on your class [Table("YourTableName")]</para>
        /// <para>conditions is an SQL where clause and/or order by clause ex: "where name='bob'"</para>
        /// <para>Returns a list of entities that match where conditions</para>
        /// </summary>
        /// <typeparam name="T"></typeparam>
        /// <param name="connection"></param>
        /// <param name="conditions"></param>
        /// <param name="whereParameters"></param>
        /// <returns>Gets a list of entities with optional SQL where conditions</returns>
        public static IEnumerable<T> GetList<T>(this IDbConnection connection, string conditions, object whereParameters)
        {
            var currenttype = typeof(T);
            var idProps = GetIdProperties(currenttype).ToList();
            if (!idProps.Any())
                throw new ArgumentException("Entity must have at least one [Key] property");

            var name = GetTableName(currenttype);

            var sb = new StringBuilder();
            sb.Append("Select ");
            //create a new empty instance of the type to get the base properties
            BuildSelect(sb, GetScaffoldableProperties((T)Activator.CreateInstance(typeof(T))).ToArray());
            sb.AppendFormat(" from {0}", name);

            sb.Append(" " + conditions);

            if (Debugger.IsAttached)
                Trace.WriteLine(String.Format("GetList<{0}>: {1}", currenttype, sb));

            return connection.Query<T>(sb.ToString(), whereParameters);
        }

**Comment by ericdc1** [comment]
Hello - here is an easier way to accomplish this without the helper:

conn.Query<Contact>(@"SELECT * From Contacts Where lastname like @letter", new { letter = letter + "%" }).ToList();

**Comment by mauroandrea** [comment]
Hi Eric!

Yes, I know that I can use Dapper in that way but I need to manually build my SQL sentence and the idea is to use SimpleCRUD's BuildSelect method in order to take advantage of having a business entity with data annotations because, in my case, my business entity's properties does not match with columns in my table.

If you take a look at the code you'll see that I'm using your BuildSelect method to build my SQL and then I'm using Dapper's Query in that way you said. So, I can still using my business entity without building manually my query.

Regards.

Mauro
