### ISSUE TITLE
Paged lists

### ISSUE THREAD

**Issue by moxplod** [ericdc1/Dapper.SimpleCRUD#46]
i have been using simplecrud pretty heavily in my new project. Now am at a point where i need to paginate things. Would love to contribute or get started on pagination. Do you have any ideas or have you started on this as i can see it is in your future feature ideas on the readme.

**Comment by ericdc1** [comment]
I am interested in this and need it too. The hard part of this is SQL Server version compatibility and some way to support sqllite and postgres too. 

This works on all SQL Server versions 
     SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY UserID) AS Number, Users.* FROM Users) AS u
WHERE NUMBER BETWEEN ((3 - 1) * 50 + 1) AND (3 * 50)
 
 This version works on SQL Server 2012 and later 
     SELECT * FROM Users ORDER BY UserID OFFSET 100 ROWS FETCH NEXT 50 ROWS ONLY

If you want to help with the specifics for each supported database along with some tests I am all for it.

**Comment by ericdc1** [comment]
This is implemented and available as a prerelease nuget package at https://www.nuget.org/packages/Dapper.SimpleCRUD/1.9.0-beta 

I added documentation to the github project page, unit tests, and a working example in the included sample website (users page). 

If you have any comments or suggestions please let me know.
