### ISSUE TITLE
Object Multimapping

### ISSUE THREAD

**Issue by arogers77** [ericdc1/Dapper.SimpleCRUD#48]
Hello, love this library.  Is there any hope of building in the ability to use Dapper's multiple object mapping feature.  I know that I can call Dapper directly, but I am looking to see if this will be a feature that will be included in an upcoming release?  Having the ability to load an object that consists of a mix of simple and complex types could be very useful.

**Comment by ericdc1** [comment]
Thanks for the feedback. I think this is outside of the spirit of the simplecrud project. If you have a suggestion on how to implement this I am glad to discuss it with you.

**Comment by arogers77** [comment]
I have some ideas.  Working on mapping it out.  Will forward to you to get your thoughts.

**Comment by arogers77** [comment]
Hey Eric,

I am currently working on adding multimapping into SimpleCRUD.  It will probably take another week or two (still have to work).  :)  Once I'm finished, I'll send you a link to the fork so that you can check it out and if you like it, possibly add it in the master.

**Comment by ericdc1** [comment]
Thanks. I am very concerned about keeping this in the spirit of "simple".
When these overly complex scenarios come up it may be best to just use
straight Dapper. I would hate to have a dozen overloads on something like
"GetList" to cover every possible case someone could need.

Maybe this could be an extension to Simplecrud rather than totally altering
every existing method?

**Comment by ericdc1** [comment]
I think your other ticket is a good reflection of this... I added a simple
feature to allow manually specified primary keys (which I would never use)
that caused you grief. The more "non simple" stuff we tack on to this thing
the less simple and less generally useful it is to the people using it.

**Comment by arogers77** [comment]
I guess I see it like this.  You call this "SimpleCrud" and have mentioned keeping it in the spirit of "Simple". By your definition, I am assuming this means a simple object relationship with no complex types and just a handful of supporting methods.  I think you've created something pretty cool and think that definition of Simple is too limited.   You think you've just built a "simple" method for doing CRUD operations, but you've built more than that.  You've created an elegant solution to building SQL statements and using it with Dapper.  Your library is an extension that makes dapper a little "simpler" to use -- it uses a common sense approach to Dapper. Now, I know how to use dapper and directly call it to use object multimapping, stored procedures, etc.  I use SimpleCrud for some things and map to dapper directly for others.

The additional methods I was proposing would simply allow a person to use more of dapper.  The difference between my object multimap suggestion (which simply adds functionality to support more of dapper) and the other issue (hard coded values that dictate whether a field is loaded -- typically a bad idea in any framework) is huge. The two issues aren't the same.  Adding functionality to use more of dapper is generally "more" useful, not less.  

I was only offering because I really liked this extension to dapper and was excited to offer ideas in the spirit of open source.  It's cool -- I can leave it be. The idea wasn't to annoy you. Just thought I would offer to share if you were interested.

**Comment by ericdc1** [comment]
I have avoided doing things like change tracking, upsert, etc to avoid going too far but it is possible this fits in. 

Thanks for the conversation. I will definitely consider this after review.
