### ISSUE TITLE
Self-referencing table problem

### ISSUE THREAD

**Issue by talismax** [ericdc1/Dapper.SimpleCRUD#49]
This table is generated with the ParentPropertyTypeId class property column as PropertyType which is the name of the class and thus fails (there's a fk from ParentPropertyTypeId to Id): 

    CREATE TABLE [dbo].[PropertyTypes](
	[Id] [int] NOT NULL PRIMARY KEY,
	[Description] [varchar](50) NOT NULL,
	[ParentPropertyTypeId] [int] NULL
    ) 

Here's what gets generated:

       [Table("PropertyTypes")]
	    public partial class PropertyType
	    {
		[Key]
		public virtual int Id { get; set; }
		public virtual string Description { get; set; }
		public virtual int? ParentPropertyTypeId { get; set; }
		public virtual PropertyType PropertyType { get; set; }
		public virtual IEnumerable<PropertyPropertyType> PropertyPropertyTypes { get; set; }
		public virtual IEnumerable<PropertyType> PropertyTypes { get; set; }
	    }

It seems like this problem would occur on any self-referencing table. 

The EF Reverse Poco Generator generates this same table like this:

    // PropertyTypes
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.15.1.0")]
    public partial class PropertyType
    {
        public int Id { get; set; } // Id (Primary key)
        public string Description { get; set; } // Description
        public int? ParentPropertyTypeId { get; set; } // ParentPropertyTypeId

        // Reverse navigation
        public virtual ICollection<PropertyPropertyType> PropertyPropertyTypes { get; set; } // Many to many mapping
        public virtual ICollection<PropertyType> PropertyTypes { get; set; } // PropertyTypes.FK_PropertyTypes_ParentTypes

        // Foreign keys
        public virtual PropertyType PropertyType_ParentPropertyTypeId { get; set; } // FK_PropertyTypes_ParentTypes
        
        public PropertyType()
        {
            PropertyPropertyTypes = new List<PropertyPropertyType>();
            PropertyTypes = new List<PropertyType>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

I am going to dig deeper but I thought I'd give you a heads up.

**Comment by ericdc1** [comment]
I may have a solution.Change line 79 in the modelgenerator from:

		public virtual <#=tables[key.ReferencedTableName].ClassName #> <#=tables[key.ReferencedTableName].ClassName #> { get; set; }

to: 

		public virtual <#=tables[key.ReferencedTableName].ClassName #> <# if (tables[key.ReferencedTableName].ClassName==tbl.ClassName) { #>FK_<#}#><#=tables[key.ReferencedTableName].ClassName #> { get; set; }

It results in this getting generated:

	[Table("PropertyTypes")]
	public partial class PropertyType
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Description { get; set; }
		public virtual int? ParentPropertyTypeId { get; set; }
		public virtual PropertyType FK_PropertyType { get; set; }
		public virtual IEnumerable<PropertyType> PropertyTypes { get; set; }
	}
If this works for you I will add it to the nuget package.
