### ISSUE TITLE
When Insert, get Long type as return of autoincrement value 

### ISSUE THREAD

**Issue by clabnet** [ericdc1/Dapper.SimpleCRUD#52]
Hi @ericdc1,
see https://github.com/ericdc1/Dapper.SimpleCRUD/issues/39

I tried your version with my suggested implementation. It run fine but ONLY if the id autoincrement is an integer type. Yes, I known that the integer contain 2.000.000.000+ rows, but this is not known who created the database I'm working. I can't change the type id on table definitions, I must use the long type.
I would mark as deprecated my version https://github.com/clabnet/Dapper.SimpleCRUD of your code, but I can't do it until this feature is not running with this requirements.
Please feel free to contact me for other informations.
Grazie for your work.

**Comment by ericdc1** [comment]
I think this is what you need: 

https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L182 

     var id = connection.Insert<long>(new BigCar { Make = "Big", Model = "Car" });
