### ISSUE TITLE
Get<T>(this IDbConnection, object) misses transaction as parameter.

### ISSUE THREAD

**Issue by NerijusN** [ericdc1/Dapper.SimpleCRUD#53]
Most of SimpleCRUD methods has transaction parameter as optional. Get&lt;T&gt;() has no way to pass transaction so if you do Get&lt;T&gt;() in transaction scope you will get exception:

"ExecuteReader requires the command to have a transaction when the connection assigned to the command is in a pending local transaction. The Transaction property of the command has not been initialized."

please to make SimpleCRUD even more attractive add transaction to get method:

- [ ] Get&lt;T&gt;(this IDbConnection, object, IDbTransaction)

**Comment by arogers77** [comment]
Hey NerijusN,

Transactions make since on the CUD operations.  Not sure of the use case for adding a transaction for a "select" (R) statement?  Not meant to spark a flame -- more curious.  I've never come across the need to have a select statement in a transaction.  In SimpleCRUD -- none of the Get<T> or GetList<T> methods provide and IdbTransaction parameter -- which makes sense to me.  Are you attempting to use a transaction with a high isolation level?  Just curious.

**Comment by ericdc1** [comment]
I too am curious to why this is needed. I investigated this and I could add it to the code without breaking anything except for the base GetList<T> without parameters as it would create an ambiguous situation between the few GetList methods.

**Comment by NerijusN** [comment]
Hello,

Its very simple case: for more efficiency all tasks are packed into UnitOfWork (like NHybernate) and then done in one single transaction without any connection return to pool. So if inside unit of work that is inside transaction you can't read data with Get&lt;T&gt;(). Can't read data before transaction for a reason too.

**Comment by ericdc1** [comment]
Please take a look at this commit and let me know what you think. If this will work I can publish a new nuget package.

https://github.com/ericdc1/Dapper.SimpleCRUD/commit/487de20ed8efd4853df2115ed093688560ba8341

**Comment by NerijusN** [comment]
Eric, 

Pulled out source, build and copied Dapper.SimpleCRUD.dll to project, uncommented code and voalia! 

WORKS 100% ! 

Thank you very much!

PS. will it be version in nuget 1.9.0.1 is it?

**Comment by oghenez** [comment]
> Eric,
> 
> Pulled out source, build and copied Dapper.SimpleCRUD.dll to project, uncommented code and voalia!
> 
> WORKS 100% !
> 
> Thank you very much!
> 
> PS. will it be version in nuget 1.9.0.1 is it?

I also need this feature, can you share your code?
