### ISSUE TITLE
Primary Key Field Assumes 0 is Default Value

### ISSUE THREAD

**Issue by arogers77** [ericdc1/Dapper.SimpleCRUD#54]
In version 1.9.0, you added the predefined value of 0 for the ID field.  I understand why it was added, but can it be handled differently.  I (and several other developers I know) use different values for the initialization of the object/field representing the primary key (some use -1, some use int.minValue, etc.).  I initialize everything (a holdover from my days of doing C/C++ programming).  When a class model is initialized to a default value other than 0, the new identity is not loaded into the primary key field.

Can we create an attribute to determine the default value of the primary key and then compare to that attribute value (instead of hard coding 0)?  Thanks -- love your library.

**Comment by ericdc1** [comment]
Can you point out where this happened? I looked through the commits and can't seem to locate where this may have changed. 1.9 added paged lists and shouldn't have changed other existing functionality.

**Comment by arogers77** [comment]
Sure -- in the following method:

public static TKey Insert<TKey>(this IDbConnection connection, object entityToInsert, IDbTransaction transaction = null, int? commandTimeout = null)

The if/else clause states the following:

if ((keytype == typeof(int) || keytype == typeof(long)) && Convert.ToInt64(idProps.First().GetValue(entityToInsert, null)) == 0)
            {
                sb.Append(";" + _getIdentitySql);
            }
            else
            {
                keyHasPredefinedValue = true;
            }

So if the ID field value is initialized to another value (say -1), it's defined as a "predefined value" and the identity sql isn't loaded.

**Comment by ericdc1** [comment]
What do you suggest? This was added because some people wanted to specify the primary key rather than using database autogenerated numbers. See https://github.com/ericdc1/Dapper.SimpleCRUD/issues/39

If its getting autogenerated why not just leave it null?

**Comment by arogers77** [comment]
Hey Eric,

Thanks for responding.  I'm a big fan of the null object pattern -- so in my code, I return an object in all cases and verify the record "load" by comparing to the PK value and see if it is a set value (rather than checking null everywhere).  I actually think the version you had prior to this change was the right way to go.  The class models should be loaded if the query matches the conditions (default actions).  If a field shouldn't be loaded (i.e. a preset key value), could the users simply use an attribute to "ignore" the loading of data in that key field?

**Comment by ericdc1** [comment]
Except the way it was before didn't support the idea of a manually
specified primary key. If I revert it I will break that functionality.If PK
value is null it is assumed you expect it to be generated and the code
returns the new identity. If you pass in a value (-1 or 999) it assumes you
already set the key yourself and don't expect the database to do it for
you.

How do you suggest reconciling the manually specified primary key feature
and your specific desire to set the primary key value but still expect the
code to know you were just kidding?
