### ISSUE TITLE
Setting Dialect for different DB

### ISSUE THREAD

**Issue by ikocev** [ericdc1/Dapper.SimpleCRUD#56]
I am not sure if this is issue but let me try :)
I noticed in the SimpleCRUD.cs class that there is no arguments constructor with `SetDialect(_dialect);` method. Right after this we have: 
`private static Dialect _dialect = Dialect.SQLServer;`

So my question is, should we have constructor with arguments setting the sql server or? I didn't find anything on the documentation so far. I found out this using PostgreSQL, and there was error coming from Insert method "Syntax error near "["". I search through your code and found that encapsulation was issue.
Note: I installed the extension via Nuget.
Note 2: Anyway, awesome work and thanks for your time and effort developing this.

**Comment by ericdc1** [comment]
Hello,

You can use this line of code to change dialect from the default.

     SimpleCRUD.SetDialect(SimpleCRUD.Dialect.PostgreSQL); 

Here is the documentation: 
https://github.com/ericdc1/Dapper.SimpleCRUD/#database-support

I usually do this in the method I use to open the connection. Here is an example: 
https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L144

**Comment by mamcx** [comment]
This meant is not possible to talk to 2 different DB at the same time?

**Comment by ericdc1** [comment]
You can change the dialect as many times as you want in a single request.

**Comment by mamcx** [comment]
Will make more sense to set it for the connection instead. Global settings is kind of bad ;)
