### ISSUE TITLE
Oracle dialect support

### ISSUE THREAD

**Issue by jbowdeny2k** [ericdc1/Dapper.SimpleCRUD#57]
Has anybody tried to get this working with Oracle?  I was able to almost get it working by adding a dialect for Oracle and a global variable _parameterPrefix (Oracle wants ":" not "@").  However the insert returning the new key is causing me issues.  I'm going to keep working at it but I don't have a good solution for this yet.  If anybody has worked on this issue and has a good solution I'd be interested in your experience.

**Comment by ericdc1** [comment]
I haven't and unfortunately don't have ready access to Oracle. For the other databases I was able to get it to work with these 3 things (with examples) 

//what to wrap table and column names in
encapsulation  =  "[{0}]"

//what query to run to get the ID (primary key) of the newly inserted item 
IdentitySql  =  "SELECT CAST(SCOPE_IDENTITY()  AS BIGINT) AS [id]"

//query to run to perform paging 
PagedListSql = "SELECT * FROM (SELECT ROW_NUMBER() OVER(ORDER BY {OrderBy}) AS PagedNumber, {SelectColumns} FROM {TableName} {WhereClause}) AS u WHERE PagedNUMBER BETWEEN (({PageNumber}-1) * {RowsPerPage} + 1) AND ({PageNumber} * {RowsPerPage})"

For Oracle, no encapsulation is probably best - http://stackoverflow.com/questions/13798035/oracle-table-column-name-with-space 

For IdentitySQL this seems hard in Oracle as the "returning" option is in the middle of the insert statement - http://stackoverflow.com/questions/1145294/oracle-return-newly-inserted-key-value and http://needquickanswer.blogspot.com/2012/10/oracle-get-last-inserted-id-like.html 
It seems like this is the biggest barrier as it would require more intrusive changes to fit in unless you can find another way. 

For paging this is a decent start http://stackoverflow.com/questions/13738181/best-practice-for-pagination-in-oracle

Let me know what you think.

**Comment by jbowdeny2k** [comment]
I was able to get the Oracle dialect working and passing the tests except the for GUID and schema tests.  The insert method had to be modified in a less than ideal way. To get it working properly would have required more thought and effort than I was prepared to do.  At this point it will meet my needs.
