### ISSUE TITLE
Overload for DeleteList<T> to use whereConditions object

### ISSUE THREAD

**Issue by elmar-de-groot** [ericdc1/Dapper.SimpleCRUD#58]
Hi,
I'd like to add an overload to the library for both DeleteList&lt;T&gt; and DeleteListAsync&lt;T&gt; to promote the use of the whereConditions object instead of writing out the where-statement in a string. In a similar fashion to what the GetList&lt;T&gt; function does. 

Example:

    using(var db = GetDbConnection()){
        // will delete all users whose first name is equal to Test
        db.DeleteList<User>(new { Firstname = "Test" })
    }

Kind regards,
Elmar

**Comment by ericdc1** [comment]
This will be available in the next release. Thanks for the feedback.

**Comment by elmar-de-groot** [comment]
Hi Eric, I've got the source code for this as well as the unit tests should you be interested.
Cheers,

**Comment by ericdc1** [comment]
It has already been implemented and is up on Nuget.
