### ISSUE TITLE
Unable to specify schema

### ISSUE THREAD

**Issue by iseesharp83** [ericdc1/Dapper.SimpleCRUD#6]
Functions like `Get<>()` and `GetList<>()` do not work across different non-default schemas.

A work around is to provide a `TableAttribute` on the class in this fashion:

```
[Table("Schema].[Table")]
```

There might be an extended attributes that allows a fully qualified name (i.e. using three parameters - one for db, one for schema, one for table), or additional attributes such as `SchemaAttribute`.

**Comment by needo2** [comment]
> We have implemented this.

What does this mean? How do I specify schema?
