### ISSUE TITLE
Any hope of a CoreCLR lib

### ISSUE THREAD

**Issue by ronnyek** [ericdc1/Dapper.SimpleCRUD#61]
looks like dapper supprorts CoreCLR in at least a beta form, is there any chance of getting a compatible release here?

**Comment by ericdc1** [comment]
When it gets closer I will. I have been following the authors of some very notable nuget packages struggle with this since its not well documented yet.

**Comment by colin-young** [comment]
A couple months back I converted this library to CoreCLR. It wasn't all that difficult, although I didn't thoroughly test it. The biggest issues were around reflection which had some minor (but significant to the compiler) syntax changes.

**Comment by ericdc1** [comment]
While I appreciate the enthusiasm, I don't have the time to invest into building and testing something for a still unreleased version of the .Net framework. If you really need this and want to take the time to ensure all the tests pass, I will meet you part of the way and verify the tests pass and get a new Nuget package built.

I expect I will get to this on my own not long after there is a final release of Core CLR.

**Comment by colin-young** [comment]
Yeah, I wasn't posting that as a suggestion to incorporate it. It was just for the original poster in case he needed some help getting pointed in the right direction. Probably could have been more clear in the message :)

The good news is it doesn't look like this library is going to be difficult to port at all once you're ready to do so.
