### ISSUE TITLE
Ignore property on update

### ISSUE THREAD

**Issue by ghoppermaster** [ericdc1/Dapper.SimpleCRUD#63]
Hi,

I have a use case where I need some properties to be inserted but not updated. For example a 'Created' property that never changes after the initial insert (or a company / tenant ID that shouldn't be allowed to be updated). I couldn't find a solution to this, apologies if I missed anything glaringly obvious! I looked at the current property attributes but could only see ones like 'ReadOnly' and 'Editable(false)' which exclude the properties altogether.

Anyway, one workaround was to create a new property attribute called 'IgnoreUpdate'. Properties marked with the 'IgnoreUpdate' attribute will be included during insert but ignored during an update.

Comments welcomed. 

Cheers

```
/// <summary>
/// Optional IgnoreUpdate attribute.
/// Ignores the specified property during an update
/// </summary>
[AttributeUsage(AttributeTargets.Property)]
public class IgnoreUpdateAttribute : Attribute
{
}
...
private static IEnumerable<PropertyInfo> GetUpdateableProperties(object entity)
{
...
//remove ones with IgnoreUpdate attribute
updateableProperties = updateableProperties.Where(p => p.GetCustomAttributes(true).Any(attr => attr.GetType().Name == "IgnoreUpdateAttribute") == false);

**Comment by ericdc1** [comment]
I usually handle this with viewmodels. One for add item with the properties needed for add (generally excluding the Id, UpdatedDate, UpdatedBy fields) and then another for update item with the fields I want to update (generally excluding CreatedDate, CreatedBy). This way SimpleCRUD will just update the fields in the model specific to the update without having to add a bunch of attributes.

Will that work for you?

**Comment by ghoppermaster** [comment]
Hi,

Thanks for the quick response!

Yes, that would work with no problems. 

I guess I was just hoping to add the property whilst adding the other [Table] and [Key] ones to keep it simple? That way I can send the entity to a generic 'Save' type function without any extra steps.

Cheers

```
[Table("Playlists")]
public class Playlist : BaseModel
{
        [Key]
        public int Id { get; set; }

        [IgnoreUpdate]        
        public int CompanyId { get; set; }

        [IgnoreUpdate]
        public DateTime? Created { get; set; }
}

...

public static T Save<T>(IDbConnection db, T entity) where T : BaseModel
{         
	if (entity.Id <= 0)
	{
		entity.Id = 0;                
		entity.Id = Convert.ToInt32(db.Insert(entity));
	}
	else
	{
		db.Update(entity);
	}

	return entity;           
}

**Comment by elmar-de-groot** [comment]
I read this post with interest as I also ran into a similar scenario. Although I ended up using the approach described by Eric, I was thinking along the lines of the following...

One other alternative could be to extend/change the EditableAttribute to include two properties like so:

    [Editable(OnUpdate=false, OnInsert=true)]
    public int CompanyId {get; set;}

This way, you are not introducing new attributes, while the default [Editable(false)] would just be the equivalent of [Editable(OnUpdate=false, OnInsert=false)]. 

Just a idea :)

Elmar

**Comment by ghoppermaster** [comment]
Awesome... that's a much better approach! :)

**Comment by ericdc1** [comment]
I implemented this and its up on Nuget as version 1.10. There is even one new unit test (I am lazy) at https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L856 

I used these attributes:

[IgnoreSelect] - Excludes the property from selects

[IgnoreInsert] - Excludes the property from inserts

[IgnoreUpdate] - Excludes the property from updates

The reason for this is all previously used attributes were from the System.ComponentModel.DataAnnotations namespace and included as exact matches in the SimpleCRUD library. I didn't want to alter how the default Editable(false) is implemented. See this from MSDN - https://msdn.microsoft.com/en-us/library/system.componentmodel.dataannotations.editableattribute(v=vs.110).aspx 

My intent was to be able to have the models in one project and the repositories in another without both needing dependencies on SimpleCRUD as it was possible to just reference System.ComponentModel.DataAnnotations in your project since the Annotations matched SimpleCRUD.

This implementation allows you to stick with that philosophy if you want or include a reference to SimpleCRUD if you want to use the new Ignore attributes. 

Give it a try and let me know what you think. 

Eric

**Comment by ghoppermaster** [comment]
Hi Eric,

Thanks for implementing this it will be super handy! :+1: 

I will try and test it out today.

May I ask (if not too bold) that we discuss #62 further? If that was implemented then I could use the library without having to implement any custom changes my side. I will add another comment there if you have time to read it. 

Anyway thanks again for this, awesome job!

John

**Comment by elmar-de-groot** [comment]
Much appreciated and nicely implemented.

**Comment by coderabsolute** [comment]
Hi all,

Thanks for adding up the new properties, am pretty sure they are going to solve some teething problems for my project. But, it is forcing me to include the reference of SimpleCRUD library in my entities project. I have two separate projects:

Applicaton.Entities - is independent and has no dependency and this is where my POCO classes reside.
Application.DataStore - has dependency on Application.Entities and this is where my database logic resides. Dapper and Dapper.SimpleCRUD is only referenced in this project.

If I need to use the newly added properties, I need to add the dependency on Application.Entities project, pointing to Application.DataStore. 

Is my understanding correct?

**Comment by elmar-de-groot** [comment]
No need to reference DataStore in Entities that would give you a circular reference. Just, add a reference to SimpleCRUD within your Application.Entities project.

**Comment by coderabsolute** [comment]
I have a difficulty understanding and explaining others, the Application.Entities project shouldn't need to know anything about SimpleCRUD. Only Application.DataStore is dependent on Dapper and SimpleCRUID. By the way, Application.Entities is not referenced to anything, it is quite an independent project on it's own.

**Comment by elmar-de-groot** [comment]
These attributes are specific for SimpleCRUD, there is really no other way than to reference that library in your Entities project if you want to make use of them. (That's how i've done it in my projects as well)

On a personal note, by wanting to use the attributes on your entities you are in actual fact (indirectly) tying the entities to the SimpleCRUD implementation. In other words, you would not be able to substitute your DataStore implementation for something else as the new DataStore implementation will not understand those attributes. From that perspective you might as well add the reference...

However, if you want/need your Entities to remain indifferent (of the actual underlying datastore implementation) you'd have to come up with a different approach. One example that Eric mentions in this thread is to use different ViewModels for this scenario.

Ultimately, your choice

**Comment by coderabsolute** [comment]
Many thanks for your input, Elmar. There are some very specific tables that shouldn't get updated by mistake that may screw up the data integrity. I think, I may end up with ViewModels approach. Appreciate your time, Elmar! :)

**Comment by naveenkumarmark** [comment]
HI, I am using Dapper.FastCRUD and I want to ignore a field while getting results.
Are these attributes available in Dapper.FastCRUD ?
.e.g.
[IgnoreSelect], [IgnoreInsert]
