### ISSUE TITLE
Update only modified columns not supported

### ISSUE THREAD

**Issue by FourDec2014** [ericdc1/Dapper.SimpleCRUD#64]
Hi,

Is there any way to update modified entity columns only?

Currently it's seems if we not set entity property value it will update previous value to either null or empty into database table respected columns rather then just keeping it as previous value.

**Comment by ericdc1** [comment]
Interesting concept. You want to pass in a model, have SimpleCrud do a "Get" and compare each property and then make an update of only the changed columns? How about an Update method that takes in the old and new model and sorts it out from there? 

One way to do this now is to have ViewModels with only the properties you want to change but I can see where your suggestion could be useful.

**Comment by ericdc1** [comment]
I started prototyping on this and am a little stuck. I did it where you pass in the updated entity and the original entity to the update method. In the code that builds the update statement (BuildUpdateSet) I added these:

            //if the property didn't change don't update it
            if (property.GetValue(entityToUpdate, null) == property.GetValue(originalEntity, null)) continue;
            //if the new value is null don't update it 
            if (property.GetValue(entityToUpdate, null) == null) continue;

My concern is with this logic, you can't set a value to null during an update so if you have a value and want it to now be null it won't be possible. 

Any suggestions?

**Comment by FourDec2014** [comment]
Hi Erirc,

Thanks for your reply, sorry i was outside not able to reply you.

Yes your are right, we can't decide which value we have to update and kept same.
Seems like we must have to set each Viewmodel values which to entity object before going to call Update method.

First have to Get entity object by ID and then using Automapper.Mapper.Map we can map viewmodel with entity object return by Get and viewmodel must have exactly same property which we needs to update into entity object.

Thanks for your valuable response.

**Comment by FourDec2014** [comment]
Hi Eric,
Is it possible to introduce new Update method where we can pass both original entity and update entity as you have suggested above?
