### ISSUE TITLE
Save Id to object in Insert

### ISSUE THREAD

**Issue by softwareguy74** [ericdc1/Dapper.SimpleCRUD#69]
It would be nice if after Inserting an object the auto Id generated would be saved back to the Id property of the object.

**Comment by ericdc1** [comment]
Since the insert method returns the new Id, you can simply do this in your code:

            var user = new User();
            user.FirstName = "Jim";
            user.FirstName = "Smith";
            user.Age = 10;
            user.UserId = connection.Insert(user);
