### ISSUE TITLE
Allow Entities without PrimaryKey

### ISSUE THREAD

**Issue by shoaibshakeel381** [ericdc1/Dapper.SimpleCRUD#71]
Currently Each entity we work with must have an Id (Primary Key) property. How can we overcome this limitation and allow insertion without primary key.

**Comment by ericdc1** [comment]
This is fundamental to SimpleCRUD. Without a primary key you wouldn't be
able to use Get, Update, or Delete helpers as there wouldn't be a primary
key to locate the record.

I'm afraid your situation isn't the intended target of SimpleCRUD and
standard Dapper where you can define your more complex select and update
rules is more appropriate.

If you can think of a way to do something like this without a primary key
please let me know.

     connection.Delete<User>(id);

Eric

**Comment by shoaibshakeel381** [comment]
Thanx for reply. I think I'll just create separate methods for handling my scenario.
