### ISSUE TITLE
Oracle dialect support

### ISSUE THREAD

**Issue by MaximKorobov** [ericdc1/Dapper.SimpleCRUD#74]
Please implement Oracle database dialect support.

**Comment by ericdc1** [comment]
Hello - I don't have any use for this and don't have easy access to Oracle. If you are interested, the bits are in place to make this pretty easy if you know oracle. You just need to add an implementation for the Oracle dialect - see this for an example - https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUD/SimpleCRUD.cs#L46 

If you'd like it included, please add an oracle test suite to run the existing tests. Check out the Postgres and SQLite examples here. 

If you submit a PR I will figure out a way to verify the tests pass and get it included.
