### ISSUE TITLE
Return the ID (primary key) of the newly inserted record even the entity has predefined value

### ISSUE THREAD

**Issue by Serg046** [ericdc1/Dapper.SimpleCRUD#77]
`if ((keytype == typeof(int) || keytype == typeof(long)) && Convert.ToInt64(idProps.First().GetValue(entityToInsert, null)) == 0) 
{ 
    sb.Append(";" + _getIdentitySql); 
}`

Could you please change this code (and for other pk types) to be able to get the pk id even the entity has predefined value?
Or we can have any exception, for now the behavior is not good.
It's confusing... To understand why I didn't get a new pk key, I was forced to view a source code.

**Comment by ericdc1** [comment]
I am not following. The code returns the predefined value if there is one.

  if (keytype == typeof(Guid) || keyHasPredefinedValue)
            {
                return (TKey)idProps.First().GetValue(entityToInsert, null);
            }

Can you elaborate

**Comment by Serg046** [comment]
Yes, but it's not correct.

Here is the SQLite sample:
```
var team = CreateTeam();
team.Id = 5;
var id = connection.Insert(team);
```
Assume db is empty and Id column is identity. At first the team with id = 5 will be created and returned id = 5. It's correct. But when we will execute this code again the team with id = 6 will be created but Insert() method still returns 5. It's not good.
Also some database engine could have own logic for the identity columns. For example if we try to insert record with id = 5 and db is empty, the record will be inserted with id = 1.

So I think it will be useful to return a real id from the database in the all cases, even if we have a predefined value. Or we can get some exception that forces us to use Insert() method with default value to avoid any issues. Or make this as optional, anything like SetDialect()

**Comment by ericdc1** [comment]
If you don't want the ID you set returned then why are you setting it? Leave it empty and it will always return the newly generated ID.  Please review this issue from last year to see how we got here. https://github.com/ericdc1/Dapper.SimpleCRUD/issues/39

**Comment by Kenstea** [comment]
I think @Serg046  is right. In some scenarios, we cannot prevent user from manually input primary key value (intentionally or unintentionally) and still want ID return correctly. In his case, it should always a number rather than 5.

I haven't had a chance to look at Dapper code  but I will.
