### ISSUE TITLE
GetPK SQL has bug

### ISSUE THREAD

**Issue by cheetahing** [ericdc1/Dapper.SimpleCRUD#78]
T4 Template function GetPK sql
 WHERE (i.type = 1) AND (o.name = @tableName)
suggest fix by
 WHERE (i.is_primary_key = 1) AND (o.name = @tableName)

**Comment by ericdc1** [comment]
Can you explain what the bug is? Why isn't type=1 working for your scenerio?

**Comment by duginov** [comment]
type = 1 returned for columns that are part of clustered index. It is possible that Primary key and clustered index are totally different.
