### ISSUE TITLE
To add "OrderBy" to GetList<T>

### ISSUE THREAD

**Issue by coderabsolute** [ericdc1/Dapper.SimpleCRUD#81]
It would be useful to have the option to pass in the "Order By" Clause for GetList function just like GetListPaged<T>.

**Comment by ericdc1** [comment]
You can do this with the string conditions like "where name='bob' order by lastname"

it is more formalized in the paged list since you aren't getting all records but rather a page in a set.

**Comment by kiranpradeep** [comment]
@ericdc1 Can this be reconsidered? For timeseries data, to get latest/oldest entry matching some conditions, I often find myself writing where clause queries ending with _WHERE condition ORDER BY timestamp DESC_. 

Sad part is _condition_ does correctly fit as object params with in normal GetList()- still forced to write full WHERE condition just for ORDER BY.
