### ISSUE TITLE
Passing params with complex WHERE clause

### ISSUE THREAD

**Issue by mgasparel** [ericdc1/Dapper.SimpleCRUD#82]
There is currently no way to pass params along with a complex where clause. The only way to get around it (that I know of) is to do string concatenation to build the params into the where clause itself. Why can't we pass the params through GetList<T> alongside the where clause?

```
public static IEnumerable<T> GetList<T>(this IDbConnection connection, string conditions, object parameters = null, IDbTransaction transaction = null, int? commandTimeout = null)
{
    [...]
    return connection.Query<T>(sb.ToString(), parameters, transaction, true, commandTimeout);
}
```

Then you could do something like:
```
string whereClause = "WHERE age > @customerAge AND FirstName + ' ' + LastName LIKE '%' + @Name + '%'";
var customers  = conn.GetList<Customer>(whereClause, new { customerAge = 21, Name = "mic" });
```

I could submit a PR for this if you're interested

**Comment by ericdc1** [comment]
Hello,

Thanks for the feedback. I actually wrote something for this some time ago but decided against it as in the end building up a model for a complex where clause was more complex than using normal SQL and I felt using plain Dapper was a better fit. 

Your idea is actually better than what I had in mind. I was attempting something along these lines: https://github.com/tmsmith/Dapper-Extensions/wiki/Predicates 

If you want to give it a try I would be interested in including it as long as it follows this simple path. 

Eric

**Comment by coderabsolute** [comment]
Do you have plans to include Predicates?

**Comment by ericdc1** [comment]
I don't at this time but I would be glad to consider a PR that doesn't make the process harder than good old SQL.
