### ISSUE TITLE
Would be good to have the UpdateList functionality...

### ISSUE THREAD

**Issue by coderabsolute** [ericdc1/Dapper.SimpleCRUD#89]
It would be good to have the `UpdateList` functionality, since we already have DeleteList functionality. Am hoping for the `Conditional Updates`.

**Comment by coderabsolute** [comment]
I can submit a PR if you like?

**Comment by ericdc1** [comment]
Sure - give it a shot. Please do both normal and async methods and write a few tests around it. Please try to commit with as few changes as possible so I can see what changed. People often submit PRs with 100s of lines changed that are unrelated to the issue at hand and I have to reject it.
