### ISSUE TITLE
TableNameResolver.ResolveTableName(Type type) causes exception in .NET 4.0

### ISSUE THREAD

**Issue by jannesuo** [ericdc1/Dapper.SimpleCRUD#92]
Hi,

I used your pretty nice Dapper CRUD implementation on a project that targets .NET 4.0. I noticed that TableNameResolver classes ResolveTableName(Type type) threw an exception about missing method when calling Encapsulate() method on "tableattr.Name" (line 939). 
For the reference, I'm using PostgreSQL dialect.  

The problem is that it does not consider it as a string without explicitly casting the value as a string and therefore the method signature that takes "string" as a parameter wont match the call. The problem was solved by using the explicit cast.

-> For improved support, consider using explicit casts on cases where you use dynamic properties.

**Comment by bcarrella** [comment]
I had same problem with Visual Studio 2013 compile.
I solved replacing calls to Encapsulate() with SimpleCRUD.Encapsulate() because it's a static method.

**Comment by ericdc1** [comment]
can't repro

**Comment by cnzzr** [comment]
SimpleCRUD.Encapsulate()  solved my exception.
