### ISSUE TITLE
Set identity value after insert

### ISSUE THREAD

**Issue by iBener** [ericdc1/Dapper.SimpleCRUD#96]
Hi,
Why the inserted identity values does not set to the entity? Is there a reason?
If there is, I think it would be a nice feature for the `KeyAttribute`. 
Something like this:

    public class KeyAttribute : Attribute
    {
        public bool SetValueAfterInsert { get; set; } = false;
    }

**Comment by ericdc1** [comment]
It does this - see these tests 
https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L185 
https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L545
https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L941

**Comment by cremor** [comment]
As far as I can see those tests only test that the Insert methods return an id. But I think what @iBener means is that the returned id should also already be set in the key property of the object that was passed to the Insert method.

This currently only happens for Guid keys if the key is generated by SimpleCRUD. Ids that are generated in the database are returned, but not set in the key property.
