### ISSUE TITLE
Insert() throws InvalidCastException with a Guid key property

### ISSUE THREAD

**Issue by cremor** [ericdc1/Dapper.SimpleCRUD#97]
Calling the `Insert()` or `InsertAsync()` method with an entity that has a `Guid` key throws an exception:

```
System.InvalidCastException: Unable to cast object of type 'System.Guid' to type 'System.IConvertible'.
       at System.Convert.ToInt64(Object value)
       at Dapper.SimpleCRUD.<InsertAsync>d__56`1.MoveNext()
```

Note that the generic methods work fine (when given the correct key type), only the methods without the generic key parameter throw an exception because they assume an integer key.

According to the return value documentation of the non-generic methods this should work and return null.

**Comment by ericdc1** [comment]
Can you look at these tests?

https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L557
https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUDTests/Tests.cs#L545

This covers specified and unspecified GUID keys and both pass the tests. Can you give more information on your scenario and possibly write up a test showing this issue?

**Comment by cremor** [comment]
The tests only test `Insert<Guid>(new GUIDTest { ... })` and `InsertAsync<Guid>(new GUIDTest { ... })`. The generic insert method works fine, as shown by these tests.

The problem happens when you call `Insert(new GUIDTest { ... })`  or `InsertAsync(new GUIDTest { ... })` and there are no tests for those overloads.

**Comment by ericdc1** [comment]
I think that is right. The first Insert method is specifically for int primary keys. The other overload lets you specify the type so you can use GUIDs or whatever else you desire. 

` public static int? Insert(this IDbConnection connection, object entityToInsert, IDbTransaction transaction = null, int? commandTimeout = null)
        {`

In other words, the `public static int? Insert` method isn't designed to be compatible with GUID keys. Is there a reason you can't use the other one?

**Comment by cremor** [comment]
If this is by design then I suggest to update the documentation, because both the summary and the return value documentation of the non-generic `Insert` method mention that it returns null for non-integer keys.

Nevertheless, I think it would be nice if the non-generic method would work for every key type. This would be useful in something like generic repositories where you don't know the key type of the type you are currently working with.

**Comment by nerfpops** [comment]
Would have been really nice if guids were supported.

**Comment by ericdc1** [comment]
They are supported. See https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUD/SimpleCRUD.cs#L320 and read the comments above.

**Comment by nerfpops** [comment]
Amazing. Sorry for the inconvenience and thank you so much for a quick reply.

**Comment by shiva-nms** [comment]
is this issue is resolved ?

**Comment by anhnt83** [comment]
I also had problems inserting with the key type GUID

**Comment by gohalien** [comment]
> I also had problems inserting with the key type GUID

Same here

**Comment by ericdc1** [comment]
I think it works. The first Insert method is specifically for int primary keys. The other overload lets you specify the type so you can use GUIDs or whatever else you desire.

public static int? Insert(this IDbConnection connection, object entityToInsert, IDbTransaction transaction = null, int? commandTimeout = null) {

In other words, the public static int? Insert method isn't designed to be compatible with GUID keys. Is there a reason you can't use the other one?

The first method is a wrapper to make the more common integer ID easier to deal with. See the code here: https://github.com/ericdc1/Dapper.SimpleCRUD/blob/master/Dapper.SimpleCRUD/SimpleCRUD.cs#L301

If I am missing something can you provide a failing test so I can reproduce it?

**Comment by cremor** [comment]
Please see my earlier comment https://github.com/ericdc1/Dapper.SimpleCRUD/issues/97#issuecomment-248348489 for a reason why it would be good to support GUID keys in the non-generic method.

**Comment by ericdc1** [comment]
Got it. I will update the docs
